### ISSUE TITLE
System.IO.DirectoryNotFoundException

### ISSUE THREAD

**Issue by AkshantVats** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#1]
I am trying to fetch file as a stream but i am getting System.IO.DirectoryNotFoundException because the file path is like this "/document/420E-1407:Downloads/ABC.doc". I am using 6.0 android.  

 using (FileData file = await CrossFilePicker.Current.PickFile())
                {
                    //Not picking file path correctly
                    if (file != null)
                    {
                        string a = file.FileName;
                        //string b = file.FilePath;
                        var c = file.DataArray;
                       int b = a.Length;
                    }
Please fix this issue.

**Comment by jfversluis** [comment]
Thanks for reporting!

It seems to work here. Are you sure the path exists? Can you get me a reproducible project?

**Comment by AkshantVats** [comment]
It was my fault actually file not exist. Its seems working now thanks for replying.
