### ISSUE TITLE
System.MissingMethodException

### ISSUE THREAD

**Issue by ask-himanshu** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#105]
## Expected Behavior
Its working fine in Ios devices but in android, it's getting crashed.

## Actual Behavior
System.Threading.Tasks.Task`1<Plugin.FilePicker.Abstractions.FileData> Plugin.FilePicker.Abstractions.IFilePicker.PickFile(string[])

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - NuGet package version: 2.0.121
  - Platform(s): Android

Can anyone help me on this

**Comment by jfversluis** [comment]
Can you please add more code or a reproduction project? Or at least the steps on how to see this behavior?

MissingMethod sounds like you didn't install the same version on all of your projects.

**Comment by ask-himanshu** [comment]
I went through the sample projects and I have included the plugin.picker and plugin.abstraction project inside my app project and provided the reference in the main app. Because when I am installing nuget package it's showing CrossPicker cannot be found.

**Comment by jfversluis** [comment]
I’m very sorry but if you don’t provide any more (technical) details it is impossible to help you

**Comment by vividos** [comment]
I think the better way would be to use the NuGet package. You have to install it on the Forms and the iOS project if you didn't create it with the latest VS2017. Tell us the exact error messages that you get. If it's an open source project, can you share the code with us? Thanks!

**Comment by jfversluis** [comment]
If you have any further questions or issues, please reopen the issue.

Thank you for using the plugin!

**Comment by zekeriyakoca** [comment]
If you are using Xamairn Forms, you may have forgotten adding NuGet package to your Android project as well. This is one of the reasons that cause the error you mentioned.
