### ISSUE TITLE
Unable to pick a file in Android 8.0

### ISSUE THREAD

**Issue by jbtdevgit** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#107]
## Expected Behavior
Should be able to pick a file.

## Actual Behavior
CrossFilePicker.Current.PickFile() returns a null value when picking a file using an Android Version 8.0

## Specifications

  - NuGet package version: 2.0.0-beta
  - Platform(s): Android 8.0

**Comment by jbtdevgit** [comment]
Upgraded the package to 2.0121 fixed the problem

**Comment by vividos** [comment]
Good to hear! The latest version got quite some bug fixes for Android and iOS.
