### ISSUE TITLE
permission denial: opening provider com.android.providers.downloads.downloadstorageprovider

### ISSUE THREAD

**Issue by abdullam09** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#111]
## Expected Behavior
when i use xamarin forms (android project), and pick file from download folder it should read correct path and load the data to byte

## Actual Behavior
i get this error
permission denial: opening provider com.android.providers.downloads.downloadstorageprovider
READ_EXTERNAL_STORAGE enabled
WRITE_EXTERNAL_STORAGE enabled
## Steps to Reproduce the Problem

  1.pick file
  2. select file from download folder
  3. i get this error when i getStream :permission denial: opening provider com.android.providers.downloads.downloadstorageprovider

## Specifications

  - NuGet package version: 2.0.121
  - Platform(s): Xamarin Forms (Android Project)

**Comment by vividos** [comment]
On Android 6 and later you have to request permissions from the user at runtime, too. We have a PR that moves request inside the FilePicker plugin, but in the meantime you can request it for yourself. Check out the samples folder where this is shown.

**Comment by abdullam09** [comment]
i am using the code from the example "CheckPermissionsAsync", and when i pick a file first time i get asked for permission.
this error happens when i use download or google drive folders, but it works fine with videos and pictures.
i tested on 2 phones both of them android 8.1

**Comment by abdullam09** [comment]
this is my code
![annotation 2018-11-17 092436](https://user-images.githubusercontent.com/6450491/48654774-a0bcb000-ea4a-11e8-89e7-25816c9eb7a1.jpg)

**Comment by pictos** [comment]
@abdullam09  did you make a file provider in manifest.xml?

**Comment by rameshupadhaya** [comment]
I'm facing the same issue from day before yesterday. I've also tried the latest Beta versions but its not working. 

File provider is added to AndroidManifest.xml
Permissions Check is also proper.

It's only not working for the Downloads screen.

If you try to upload from file manager it works.

I'm not able to figure out what is the issue. From Downloads Screen it returns a Content Uri which causes 
**System.IO.DirectoryNotFoundException: Could not find a part of the path "/content:/com.android.providers.downloads.documents/document/2038"**

**Comment by abdullam09** [comment]
How to add permission to AndroidManifest.xml?

**Comment by pictos** [comment]
@abdullam09 In this readme you can find that...
https://github.com/jamesmontemagno/MediaPlugin/blob/master/README.md

and in this link: https://drivy.engineering/android-fileprovider/

**Comment by pictos** [comment]
@abdullam09 is it solved your problem?

**Comment by abdullam09** [comment]
Sorry, i didn't try it out yet, i will reply after i do.

**Comment by abdullam09** [comment]
i tried to apply it and still getting this error
java.io.FileNotFoundException: content:/com.android.providers.downloads.documents/document/72 
here is what i did
1- i create xml file file_provider_paths.xml
2- add this in it
```
<paths xmlns:android="http://schemas.android.com/apk/res/android">
  <files-path name="Download" path="Download/"/>
  <files-path name="document" path="document/"/>
</paths>
```
3- add this to AndroidManifest.xml
 ```
<provider android:name="android.support.v4.content.FileProvider" android:authorities="${applicationId}.myfileprovider"
        android:exported="false"
        android:grantUriPermissions="true">
        <meta-data
            android:name="android.support.FILE_PROVIDER_PATHS"
            android:resource="@xml/file_provider_paths"/>
      </provider>
```
4- add this to MainActivity

 ```
public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
        {
            PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }
also in Oncreate
```
`Intent.AddFlags(ActivityFlags.GrantReadUriPermission);`

and still same issue.

**Comment by vividos** [comment]
@abdullam09 I looked at your code and you're creating a UploadFiles object that is then used as an ItemsSource in a ListView. What we don't see is that the FilePath is bound to an ImageSource for an Image element. I think the image element can't handle Android content Uris. You have to create the ImageSource using FilePath.GetStream() instead. No need for implementing a file provider here.

**Comment by abdullam09** [comment]
@vividos , well for this i am only showing the name of the file in the listview, i use the path to upload the file to a server, also i want to upload any type of files not only images, i did further testing and i found that files downloaded from chrome can't be picked with real path. i don't know if that helps

**Comment by vividos** [comment]
Then you have to store the file to your local storage first and use the real path, or you have to use the steam returned from GetStream(). Hopefully your upload class supports uploading via stream. On Android is the safest way to get at the content.

**Comment by abdullam09** [comment]
@vividos , getting the byte array solved the problem, i tried this before i open this ticket, and the byte array was empty. i think after adding the permissions in AndroidManifest.xml, fixed the byte array.
thanks everyone for the solutions you provided. you are the best :)

**Comment by vividos** [comment]
@abdullam09 You're welcome!

**Comment by Aculeo** [comment]
Just an FYI for others having the same issue. The problem might be the delay between selecting the file and actually opening the stream.

In my case, the user can select multiple files for submission. But I didn't open the streams until the user hit submit, and that's when I had the same error. Now I'm calling `GetStream()` immediately, but wait until the user hits submit to read from the streams - problem solved.

**Comment by vividos** [comment]
Thanks for the note. I think I mentioned it in the readme, but I will check
