### ISSUE TITLE
Are permissions really needed on Android?

### ISSUE THREAD

**Issue by ChristianKleineidam** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#112]
I created a pull request that requested the permission on run-time but I just found a [StackOverflow ](https://stackoverflow.com/questions/48045626/chooser-created-with-createchooserintent-title-doesnt-display-a-title) answer that says:

>  "Does ACTION_GET_CONTENT with setType("image/*) not need a permission to read external storage?" -- correct. On Android 4.3 and older, you do not need a permission to read external storage in general. On Android 4.4+, ACTION_GET_CONTENT should return a Uri with a content scheme, not a file scheme, and you have temporary rights to access the content identified by that Uri. 

If that's the case, maybe the FilePicker Plugin can work completely without permissions on Android?

**Comment by vividos** [comment]
Well, you may not need a permission to read external storage, but often the picked files come as a content:// link, e.g. the Google Drive or OneDrive apps return that. For content:// Uris you need to use Android's ContentResolver to access the stream, as there are no actual physical files involved.

Technically, picking a file also doesn't need the permission, but the developer will immediately access the file using FileData.DataBytes or FileData.GetStream(), and then the permission is needed. So it's a user experience decision if you ask for permission first and then start picking, or if you start picking and then ask for the permission. With the current code the plugin user has the choice, and the sample just asks for permission first.

Your PR #109 puts asking for permission first, which I think is a good thing, since we got some issue tickets complaining about why picking throws an exception that permissions are not set. Do you now reconsider? I was going to merge the PR today...

**Comment by ChristianKleineidam** [comment]
I think my PR is a clear improvement over the status quo. I however get the feeling that the expection that exists is unnecessary:

It gets currently thrown in Plugin.FilePicker.Android/FilePickerImplementation.cs via: 

            if (this.context.PackageManager.CheckPermission(
                Android.Manifest.Permission.ReadExternalStorage,
                this.context.PackageName) == Android.Content.PM.Permission.Denied)
            {
                throw new InvalidOperationException("Android permission READ_EXTERNAL_STORAGE is missing or was denied by user");
            }

It might be that we could simply remove the portion of the code that throws the expection and be good.

**Comment by ChristianKleineidam** [comment]
I think my PR is a clear improvement over the status quo. I however get the feeling that the expection that exists is unnecessary:

It gets currently thrown in Plugin.FilePicker.Android/FilePickerImplementation.cs via: 

            if (this.context.PackageManager.CheckPermission(
                Android.Manifest.Permission.ReadExternalStorage,
                this.context.PackageName) == Android.Content.PM.Permission.Denied)
            {
                throw new InvalidOperationException("Android permission READ_EXTERNAL_STORAGE is missing or was denied by user");
            }

It might be that we could simply remove the portion of the code that throws the expection and be good.

**Comment by vividos** [comment]
Hmm but how do you communicate to the developer that the permission has to be added to the Android manifest? I agree on the case when the user refused granting permission; then we could just return null. Error handling is always need when calling PickFile() - who knows what Google does require in Android 10 :-D

**Comment by ChristianKleineidam** [comment]
I don't think that's something that's needed to be communicated to the developer. If the thing I quoted above is correct it seems like the permission doesn't have to be added on Android 4.3 and older to the manifest at all (only 3% of the devices that are out there run something older).

I would expect that Android manages to throw it's own error message when running on 4.2 and the user actually needs the permission.

For many people who use that plugin this error message is the only reason they currently have to have the permission and they will be able to remove the permission from their manifest when that code is gone (or otherwise only gets displayed below 4.3).

**Comment by vividos** [comment]
I put in the check for the permission so that the user gets a clear message with a defined exception text that is also mentioned in the README.md, where it can be found in the Troubleshooting sections.

I'll merge the PR #109 anyway and we'll see how users accept it. What do you think?

**Comment by vividos** [comment]
I'm not entirely satisfied with the exception thrown on API <= 23 and user forgot to add READ_EXTERNAL_STORAGE permission. What do you think about that: We add the permission automatically for the user, just like the MediaPicker plugin from James Montemagno does it:
https://github.com/jamesmontemagno/MediaPlugin/blob/master/src/Media.Plugin/Android/ManifestInfo.cs

**Comment by ChristianKleineidam** [comment]
I think a sizeable portion of the developers who use the plugin won't release versions for below API level 18 (Android 4.3) and it seems that above that point the permission is not required.

When a user downloads an App there a benefit on asking the user for less permissions and thus I think the developers who don't develop for <18 would prefer the permission not to be there. It's analog to how the Windows UWP plugin of the FilePicker doesn't need any permission.

Is it possible to do different assembly based on the API level?

**Comment by vividos** [comment]
Well, as soon as your use picks a file that is on external storage, you need the permission, and you can't add it dynamically, it must be present in the manifest. Starting from Android 6.0 you have to ask the user at runtime to grant the permission, too. So I don't know how you would handle the case where you didn't add the permission but the user picked a file on external storage.
The question is if the plugin NuGet adds the permission or the adds it.

**Comment by ChristianKleineidam** [comment]
It seems to me that you need the permission for reading files with the `file://`-scheme but not files with the  `content://`-scheme.
Starting Android 4.3 (API level 18) the picked file gets passed with the `content://`-scheme and thus no permission is needed. If you think there still a permisssion needed, where do you think that need comes from?

**Comment by vividos** [comment]
Ok maybe it's the other way around. As soon as the user picks a file on an actual storage, e.g. external SD card, the app needs to have the permission. How do you handle this?

**Comment by ChristianKleineidam** [comment]
Let's say this plugin is installed on AppA. When the intent with Intent.ACTION_GET_CONTENT is send another app will listen to the intent AppB. 

AppB will usually a system provided app but it's also plausible that another app listens to the intent. AppB needs the permission to access storage. AppB implements a FileProvider that allows it to pass a reference to the file with the `content://`-scheme as an answer to the intent (and a flag that provides the permission to access the file).

I don't think whether or not the file is located on an external SD or on internal storage has any bearing for the ability of AppB to pass the reference to the file via the `content://`-scheme.

Only on devices under Android 4.4 (API level 19) the file that gets passed back might be under the `file://`-scheme and thus it's only necessary for those to have the permission.

**Comment by vividos** [comment]
I just checked with the project's sample app and I picked a file from my download folder. I got back a part to storage, not a content:// Uri. Now what? In order for the file to be read by the sample app, the app must have the permission to access storage.

**Comment by ChristianKleineidam** [comment]
Okay, then what's written in the linked post feels strange.  =It seems to make sense to have the permission. Having it via in the way of the MediaPlugin might make it more user-friendly.

**Comment by vividos** [comment]
I just added some changes as we discussed. Available in NuGet package 2.0.133-beta. Closing this issue then.

**Comment by ChristianKleineidam** [comment]
Okay, then what's written in the linked post feels strange.  It seems to make sense to have the permission. Having it via in the way of the MediaPlugin might make it more user-friendly.
