### ISSUE TITLE
Poll: Remove SaveFile() and OpenFile() methods from plugin?

### ISSUE THREAD

**Issue by vividos** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#113]
This plugin was forked from the original Plugin project on https://github.com/Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows/ and the original project started with just the PickFile() method. @rafaelrmou  then added OpenFile() and SaveFile(), and from digging through the git history of the original project it seems the methods never worked (Android) or are of limited use.

With this issue I want to discuss and gather infos about how the different projects are using them. From the names of the methods I also figured that some users have wrong expectations of what the methods would do. When nobody uses these functions, I would like to mark the methods [Obsolete] starting from NuGet version 2.1 and then remove them in 2.2.

What do you think, users of this plugin?

**Comment by jfversluis** [comment]
I agree, they don't seem to work (that well) and I think we should keep the scope tight for this plugin. It is about picking files, retrieving the contents and path and then it is up to the user what to do with that.

As long as we can make the transition as smooth as possible (Obsolete first, then remove), fine by me!
