### ISSUE TITLE
Figure out a better way to arrange our builds in terms of beta/non-beta

### ISSUE THREAD

**Issue by jfversluis** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#115]
Right now, I have to manually remove and add the -beta tag for Nugets. This isn't ideal seeing I am the only one with access. Figure out a way to do this better.

**Comment by jfversluis** [comment]
Implemented it now like this: https://montemagno.com/continuous-integration-delivery-for-net-libraries-with-vsts/

Still need to do the releasing to NuGet part, but that isn't the hardest :)

**Comment by vividos** [comment]
The multi targeting PR already builds the NuGet package, so the only missing step should be uploading it. Good work!

**Comment by vividos** [comment]
Azure DevOps looks good! What I would like to keep is the Semantic Versioning (increase first version number on major changes, second version number on API additions and third number on minor changes). The other Xamarin plugins always confused me if I can update without worries or not. What do you think?

**Comment by jfversluis** [comment]
Hm I think it went to 2.1.0.increment now right? And we had 2.1.increment? Makes sense...

**Comment by jfversluis** [comment]
Fixed version number. And uploading NuGets works. I think I need to rearrange a little bit. Right now each PR that is verified produces a new NuGet which might be a bit much. So I would like to have a CI build that verifies changes, and one build definition that only triggers when code is actually merged and only then produce a version that starts at MyGet and can then go to NuGet beta and then NuGet production.

**Comment by jfversluis** [comment]
Split PR verification and merged code into two builds. I think this is done for now!

**Comment by vividos** [comment]
From what I understood from James' blog article was that the build always goes to MyGet, and he can approve the builds to go to NuGet beta or NuGet release stage.
