### ISSUE TITLE
How to allow only PDF files for selection in file picker?

### ISSUE THREAD

**Issue by normanchia** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#119]
Would like to ask how do i only allow PDF files for selection? I am using this plugin for Android and iOS .

**Comment by jfversluis** [comment]
You can do it like this: `var pickedFile = await CrossFilePicker.Current.PickFile(fileTypes);`

Then depending on the platform, you will have to supply a string array of files that can be opened, but the values can vary between different platforms.

For instance, have a look at this for images:

```
    if (Device.RuntimePlatform == Device.Android)
    {
        fileTypes = new string[] { "image/png", "image/jpeg" };
    }

    if (Device.RuntimePlatform == Device.iOS)
    {
         fileTypes = new string[] { "public.image" }; // same as iOS constant UTType.Image
    }
```

For PDF it would probably be something like `application/pdf` for Android and `com.adobe.pdf` for iOS

**Comment by normanchia** [comment]
I can able to do upload and preview of image, but is there a way for me to upload and preview a document like PDF?

**Comment by jfversluis** [comment]
I'm sorry, I don't understand your question. But I think what you are asking is beyond the scope of this plugin. This library only provides picking a file, it does nothing extra to support previewing or uploading or nothing besides being able to access the filesystem, select a file and return info on that file.

**Comment by normanchia** [comment]
Alright! Thank you very much for your help!
