### ISSUE TITLE
Under WPF the FilePicker can't be found

### ISSUE THREAD

**Issue by ChristianKleineidam** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#122]
In my App the FilePicker works in UWP/Android/iOS/macOS. When I click on the button for the FilePicker on XPF I get the error:

```
Exception thrown: 'System.IO.FileNotFoundException' in MyProject.dll
An unhandled exception of type 'System.IO.FileNotFoundException' occurred in MyProject.dll
Could not load file or assembly 'Plugin.FilePicker, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
```

Does the XPF plugin need any special setup? Does it work for other people?

## Specifications

  - NuGet package version: 2.1.11-beta
  - Platform(s): WPF

**Comment by vividos** [comment]
I tried it out with the sample project, but before the change to use multi-targeting. Can you also reproduce the error with the sample project?
What .NET framework does the WPF project target?

**Comment by ChristianKleineidam** [comment]
I tested with the 4.6.1 and 4.6.2 .NET frameworks. 
I created a [sample project ](https://github.com/ChristianKleineidam/TestApp/tree/12bad73ed8d8aa50d810a813d8170137848a748c) that compiles WPF and gets a `System.NotImplementedException`.

**Comment by ChristianKleineidam** [comment]
When I try to build the sample project in the FilePicker project I get the error:
```

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS2001	Source file 'C:\Users\Christian\source\repos\FilePicker-Plugin-for-Xamarin-and-Windows-1\samples\Plugin.FilePicker.Sample.Forms\WPF\Properties\Resources.Designer.cs' could not be found.	Plugin.FilePicker.Sample.Forms.WPF	C:\Users\Christian\source\repos\FilePicker-Plugin-for-Xamarin-and-Windows-1\samples\Plugin.FilePicker.Sample.Forms\WPF\CSC	1	Active
```

**Comment by vividos** [comment]
Found the initial error; there was no .NET Framework assembly, so under WPF the ".NET Standard" version was used, which has no implementation. Will be fixed when #124 is merged.

**Comment by ChristianKleineidam** [comment]
Great, it now works for me.

**Comment by vividos** [comment]
Thanks for verifying!
