### ISSUE TITLE
How to keep picked file type?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#127]
Thank for you plugin it's working good!
I want to pick file .JPG, .PDF and upload to cloud drive, How to keep type of file after picked (.JPG, .PDF)?
Thank!

**Comment by vividos** [comment]
After picking you can look at the FileName property and get the extension using Path.GetExtension() and decide what to do. Hope that helps you!

**Comment by vividos** [comment]
Closing this issue, since there were no more follow-up questions.
