### ISSUE TITLE
System.NotImplementedException: This functionality is not implemented in the portable version of this assembly

### ISSUE THREAD

**Issue by riejoanne** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#128]
## Expected Behavior
Able to pick file for Android

## Actual Behavior
Unhandled Exception:
System.NotImplementedException: This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

## Steps to Reproduce the Problem
  1.  (NuGet reference is PackageReference) Get NuGet package version 2.1.12-beta, installing package in Shared and Android project. 
  3. call CrossFilePicker.Current.PickFile() in shared project, the exception occurred.
  4. Downgrade version to 2.0.135, it's working!

## Specifications
  - NuGet package version: 2.1.12-beta / 2.0.135
  - Platform(s):  Xamarin.Android API 23

**Comment by vividos** [comment]
@riejoanne Please check out the Troubleshooting section of this github repository's Readme.md. There the error is described, and the necessary workaround. You have to also include the plugin in your Android project.

**Comment by riejoanne** [comment]
> @riejoanne Please check out the Troubleshooting section of this github repository's Readme.md. There the error is described, and the necessary workaround. You have to also include the plugin in your Android project.

The plugin have been installed in Shared and Android project(using the NuGet PackageReference mechanism)
Under the same conditions,  I'm getting the issue in lastest version 2.1.12-beta but version 2.0.135 works fine.

**Comment by vividos** [comment]
Thanks for the feedback, I'll have a look. If your project is open source, do you have a link to it, so that I can try it out?

**Comment by riejoanne** [comment]
Im afraid I cant post full source code here, since Our project is not open source. so I just made a demo, hope this help. [Demo](https://github.com/riejoanne/FilePickerDemo)
Thank you for taking the time to check the problem. This plugin help me a lot.

**Comment by vividos** [comment]
I think I found the error. 2.1.12-beta only supports MonoAndroid90 as TargetFrameworkVersion. We fixed that in PR #125, but there's no newer NuGet package yet.
@jfversluis could you publish the latest build as beta package? Thanks

@riejoanne If you don't wanna wait, you can set your TargetFrameworkVersion to 9.0 and it should work. I should put a note to the Readme.md that a certain minimum TargetFrameworkVersion is needed.

**Comment by jfversluis** [comment]
Done https://www.nuget.org/packages/Xamarin.Plugin.FilePicker/2.1.14-beta

Please let us know if this fixes it @riejoanne

**Comment by riejoanne** [comment]
Confirmed fixed in this version!! @vividos @jfversluis thank you very much!!

**Comment by jfversluis** [comment]
Great! Glad to help!
