### ISSUE TITLE
Code format and C# in general improvements

### ISSUE THREAD

**Issue by jzeferino** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#13]
Can I PR a full code reformat to match default VS/VS for mac format and change some code to use new C# features?

**Comment by jfversluis** [comment]
I'd prefer not. If someone isn't using VS4Mac they will reformat it back and we keep going back and forth. New C# features are OK, but not sure if I would want them as a separate PR. I would rather have them as part of some refactoring while implementing new features or squashing bugs.

Also try to create PRs with some more body. Just a link in the README can easily be part of something bigger IMHO.

**Comment by jzeferino** [comment]
I usually work with small commits to help revert when necessary, but in this case I will try to aggregate it.

**Comment by jfversluis** [comment]
I totally agree on keeping commits small, but I'd group logical pieces of code which actually add value. Just one line in a README seems a bit much. But ultimately it all comes down to taste 🙂
