### ISSUE TITLE
How to get file extension from Google Drive file?

### ISSUE THREAD

**Issue by raphaelsilvasage** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#130]
When I select a file from Google Drive, the "FileName" and "FilePath" doesn't return file extension (just the file name), even if I use Path.GetExtension.

How can I get the file extension from a Google Drive picked file?

This is happening on an Android device, with the 2.0.135 version
Thanks

**Comment by raphaelsilvasage** [comment]
I've tested on an Android device

**Comment by ChristianKleineidam** [comment]
I don't think you can count on there being a file extension on Android. On Android the type of a file frequently gets communicated via mime types.

On the Huawei devices I tested, there wasn' event a file extension for picking files from the storage of the phone.

**Comment by vividos** [comment]
The FilePicker tries hard to get an actual FileName property that contains the file name, e.g. by asking the FileProvider (e.g. Google Drive) for the underlying filename. Some file provider are not supporting that Query(), and that's what you are seeing. It's best to restrict picking to some well-known MIME types that you are expecting, and do a "magic bytes" check if it's the proper file format that you were expecting. Or just tell the user that the file picked is in the wrong format.
You can use the sample app to see what picking returned for FileName and FilePath, it's in the two lines below the button.

**Comment by vividos** [comment]
Closing this issue as there weren't any follow-up questions.

**Comment by Depechie** [comment]
I would suggest to reopen this issue... I have the same problem and I don't see an actual call to try to get an extension based on the MimeType ( or am I missing something? ).
Somewhere after https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/blob/master/src/Plugin.FilePicker/Android/FilePickerActivity.android.cs#L210 I would think there should be an extra check on the FileName to see if it has an extension and if none is available following code should be added:

`extension = MimeTypeMap.Singleton.GetExtensionFromMimeType(cr.GetType(uri));`

**Comment by vividos** [comment]
Well, if all else fails, the file picker plugin could call that method and return a "filename.ext" dummy filename, so that the user could at least check the file extensions. We're happy to accept any PRs that would do this. Reopening the ticket.

**Comment by Depechie** [comment]
Yeah was thinking of submitting a PR, but the code base we use ( and where I now added that functionality ) differs from this implementation and I do not have enough background to asses if an addition in this repo will not have too much impact on current usage :/

**Comment by vividos** [comment]
You can also share the code that you think fixes that issue and we're trying to incorporate it into the code base.

**Comment by Depechie** [comment]
@vividos I would add following to the IOUtil.Android.cs
```
        public static string GetExtensionFromMimeType(Context context, Android.Net.Uri uri)
        {
            return MimeTypeMap.Singleton.GetExtensionFromMimeType(context.ContentResolver.GetType(uri));
        }
```

But where it should be called from is not that clear for me... I would assume at a certain point you would like to return a path to a selected file. So as long as that path has no FileExtension, you can try to get one from the method shown above.

**Comment by vividos** [comment]
@raphaelsilvasage @Depechie Could you test with the latest FilePicker NuGet, 2.1.41-beta, if the picked files are now returned with an extension? Thanks!
