### ISSUE TITLE
Can't navigate to images

### ISSUE THREAD

**Issue by AndAShape1** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#132]
Why am I unable to navigate to the images folder? All I can see is iCloud storage.

**Comment by jfversluis** [comment]
I'm afraid we're going to need a little bit more info.

Can you reproduce this? Do you have any code to show that you are using? What are you expecting to see?

**Comment by FruitAndAShape** [comment]
Picker is opened with this...  `var file = await CrossFilePicker.Current.PickFile();`

In the simulator, this all that appears...

<img width="280" alt="Screenshot 2019-04-18 at 13 23 42" src="https://user-images.githubusercontent.com/7421691/56360669-41232600-61dd-11e9-9c80-13960f68d431.png">

**Comment by AndAShape1** [comment]
Picker is opened with this...

`var file = await CrossFilePicker.Current.PickFile();`

In the simulator, this all that appears...

<img width="280" alt="Screenshot 2019-04-18 at 13 23 42" src="https://user-images.githubusercontent.com/7421691/56360749-762f7880-61dd-11e9-8e4a-8a1fa3e03c81.png">

**Comment by jfversluis** [comment]
Since iOS does not allow access to the filesystem as Android does, I think this is all that is available on iOS.

If you want to pick images, you should have a look at the [MediaPlugin](https://github.com/jamesmontemagno/MediaPlugin)
