### ISSUE TITLE
Filepath Format

### ISSUE THREAD

**Issue by bluekuen** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#136]
Hello, i need help on getting the creationData of a picked File.
I guess the path from the picked FileData.FilePath is not in the correct format or do i need to convert it?
My attempt to get the File CreationTime is following:

DateTime creationTime = File.GetCreationTime(fileData.FilePath);

The FilePath i get is:

content://com.android.externalstorage.documents/document/home%3Astatistic%2F12345678_123.100

What i need is:
/storage/emulated/0/Documents/statistic/12345678_123.100

So my Question is, is there a way to convert it to the needed path ?

**Comment by vividos** [comment]
On Android the transfer between different apps is managed through content provider, which use the content:// URL scheme. Depending on the app, there may not be a real file at all. The FilePicker plugin tries hard to get you an actual file path, but when you get a content URL, you may be able to query extra Infos about the file. See the Android implementation on how to do that.

**Comment by vividos** [comment]
You can look at the code in GetDataColumn() and try to get some other fields in your code:
https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/blob/master/src/Plugin.FilePicker/Android/IOUtil.android.cs#L143
That may help, but it may be that not all content provider return all fields.

Does that help you?

**Comment by muffadal53** [comment]
> You can look at the code in GetDataColumn() and try to get some other fields in your code:
> https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/blob/master/src/Plugin.FilePicker/Android/IOUtil.android.cs#L143
> That may help, but it may be that not all content provider return all fields.
> 
> Does that help you?

Can you guide on how to get the real file path using "Content" path returned file FilePicker in Xamarin forms?

**Comment by vividos** [comment]
There may or may not be an actual filename. What's your real use case here? What do you try to accomplish?

**Comment by muffadal53** [comment]
> There may or may not be an actual filename. What's your real use case here? What do you try to accomplish?

@vividos : My usecase is that when I try to use FilePicker plugin and select any file from "Documents" folder or select any file using Google Drive, the "FilePath" I get after selecting some file e..g ".pdf" is returned to me as Content path i.e. starting with "content://" and not the actual file path, which I can use to perform File Operations using "System.IO"(e.g. File.Exists()). But if I select any file from "Downlaod"/"DCIM" or any custom folder created by me I get the FilePath correctly e.g. "/storage/emulated/0/Pictures/Messages/imagename.jpg".  So, how do I achieve this for the usecase I mentioned above in my "**Xamarin Forms**" application.

Example: If I use Gmail to attach any file by selecting any file from "Documents" folder or "Google Drive" folder, it is able to attach that file. So, how can I achieve the same using FilePicker plugin.

Help is really appreciated.

**Comment by vividos** [comment]
That's not you use case, that's the implementation. A use case would be "the user can pick a file and then it's uploaded to a Backend Service dir processing"; then I would recommend to store the picked file to a temporary file. Or it could be "the user wants to pick a file and then display as image"; then you could just put the steam in an ImageSource. In my app I load kml and kmz files via SharpKml, and it happily accepts a Stream instance.

**Comment by muffadal53** [comment]
@vividos: I just gave you the use case of how or from where I am selecting the file to upload on Android.But my real usecase is after selecting the file I upload it to the Backend Server/Cloud. So, can you kindly guide me on how to get real path from "Content" path using FilePicker when I select it from Documents folder or any file from Google Drive application. And I didn't get your point about kml and kmz files via SharpKml.I don't know what is SharpKm.Is SharpKml some application?

**Comment by vividos** [comment]
You can easily google SharpKml, but in your case it's best to store the Stream object you get from picking the file to a temporary file. After all, you have to upload it to a backend server. Imagine you have to retry uploading when the user is offline, and the picked file is already gone. You can easily do that with opening a FileStream in a temporary folder (e.g. your Android cache folder) and use the Stream.CopyTo() method.

Please also try to understand what I wrote in the second comment. There may not be a physical file on the device at all. Thank you!

**Comment by muffadal53** [comment]
@vividos: So, are you saying if use the Stream object from FileData for the selected file (from location like Documents or Google Drive), and store it in temporary file, I would be able get the real file content to upload on to Backend server?

Also, how do I get to know if there is a real file or not before storing it to temporary file?

**Comment by vividos** [comment]
Well, since you create the temporary file for yourself, you already have the file name, so you can use it for upload. You can also use the Stream object directly, e.g. as POST content in a HttpClient call.

**Comment by muffadal53** [comment]
@vividos:K.But how will I get the correct "File Name" for Content path returned by FileData in order to upload the File with same name on the server using temporary file? Should I use fileData.FileName property?


Also, how do I get to know if there is a real file or not like you have mentioned in your second comment, before storing it to temporary file? Do I need to check something on Stream.

**Comment by vividos** [comment]
In any case you should:
- create a temporary file (https://docs.microsoft.com/en-us/dotnet/api/system.io.path.gettempfilename?view=netframework-4.8)
- in your app's cache folder (https://docs.microsoft.com/en-us/dotnet/api/Android.Content.Context.CacheDir?view=xamarin-android-sdk-9), then
- create a FileStream (https://docs.microsoft.com/en-us/dotnet/api/system.io.filestream?view=netframework-4.8) and
- call Stream.CopyTo() to save the file (https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.copyto?view=netframework-4.8).
- The filename you generated in the first step can be used to upload the file, e.g. HttpClient.PostAsync() (https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.postasync?view=netframework-4.8) or any other means.

For your question about the FilePath: Either it contains a real file path (FilePicker plugin tries hard to get the path) or it contains a content:// URI; in either case it's safer for your app to store it locally, as the user can delete the file at any time.

I'm closing this issue, as my explanations should lead you to a working solution, and it's ultimately not about the FilePicker plugin. Please also check out Microsoft Learn (https://docs.microsoft.com/en-us/learn/), there are many tutorials and videos, all about the techniques I mentioned, and it's all free.

**Comment by muffadal53** [comment]
@vividios: I will try the approach suggested by you.But if it is not about FilePicker plugin then why does it return two types of FilePath while selecting file from different locations on Android? First the correct file path and second the Content:// type path.

**Comment by vividos** [comment]
This is how Android handles transfer between different apps, and file picking is not different. Please read up on content providers in the Android documentation if you want more infos on this. Thanks!
