### ISSUE TITLE
Android: It allows selection of .mp4 file, Even though it is not mentioned in "allowedTypes" filter. 

### ISSUE THREAD

**Issue by muffadal53** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#137]
## Expected Behavior
It should not allow selection of .mp4 file as it is not mentioned in the "allowedTypes" file filter. 

## Actual Behavior
It should allow selection of only those files which are mentioned in "allowedTypes" array.

## Steps to Reproduce the Problem
I have added "allowedTypes" filter to allow file types of "*.png, *.jpeg and *.pdf*" format. But the picker also allows me to select ".mp4" file, Which I don't want. So, do I need to do something more to removed "*.mp4" file selection or this is a known issue? Kindly let me know.

`allowedFileTypes = new string[]
             {
                    "image/png",
                    "image/jpeg",
                    "application/pdf"
             };`
  - NuGet package version: 2.1.18
  - Platform(s): Android 9.

**Comment by vividos** [comment]
On my device the files that don't match the given MIME types are grayed out and can't be selected. I'll have to test this on my device with your code line. Is the code in an open source project that we can look at?

**Comment by muffadal53** [comment]
> On my device the files that don't match the given MIME types are grayed out and can't be selected. I'll have to test this on my device with your code line. Is the code in an open source project that we can look at?

@vividos : Sorry my project is not opensource. But, if you specify the filter of allowedFilesTypes as mentioned above and if you have video file in your gallery of android device (Mine is Samsung S8) it will still allow you to select this video file which it should ideally not allow.

**Comment by vividos** [comment]
I tried out your `allowedFileTypes` line in the Samples app in this repository, and put it in the `PickImage_Clicked()` method of the `MainPage`, and I couldn't pick .mp4 files, only the MIME types mentioned. Can you double check that you are passing `allowedFileTypes` to PickFile()? If yes, we maybe have to see more of your code to analyze the problem.

I have one more idea: When Android downloads a file, the file is put in the Downloads folder, along with the MIME type that the web server told it. So if the web server said "hey, here's a file with extension .mp4, and it has MIME type "image/png", Android happily accepts it and stores the MIME type. When picking, Android then allows you to pick that file, as it has the proper (wrong) MIME type. So essentially if the web server was configured wrong, this also could happen. You can verify that it's this behavior by moving the .mp4 file to your Windows desktop and move it back into the Downloads folder (using the USB connection). When you can't select the file anymore, it was exactly this issue.

**Comment by muffadal53** [comment]
> I tried out your `allowedFileTypes` line in the Samples app in this repository, and put it in the `PickImage_Clicked()` method of the `MainPage`, and I couldn't pick .mp4 files, only the MIME types mentioned. Can you double check that you are passing `allowedFileTypes` to PickFile()? If yes, we maybe have to see more of your code to analyze the problem.
> 
> I have one more idea: When Android downloads a file, the file is put in the Downloads folder, along with the MIME type that the web server told it. So if the web server said "hey, here's a file with extension .mp4, and it has MIME type "image/png", Android happily accepts it and stores the MIME type. When picking, Android then allows you to pick that file, as it has the proper (wrong) MIME type. So essentially if the web server was configured wrong, this also could happen. You can verify that it's this behavior by moving the .mp4 file to your Windows desktop and move it back into the Downloads folder (using the USB connection). When you can't select the file anymore, it was exactly this issue.

@vividos: Yes i had passed "allowedFileTypes" to PickFile. I think it could be the case where the MIME type is "image/png" in the Downloads folder. I will try moving that file to Windows Desktop and move it back to Downloads folder using USB connection and let you know if it works fine. Thanks.

**Comment by vividos** [comment]
@muffadal53 As we didn't hear anything from you, I consider this issue solved. Thanks for reporting!
