### ISSUE TITLE
Android (Chrome OS): Picking a file doesn't close the file picker menu

### ISSUE THREAD

**Issue by ivml** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#139]
## Expected Behavior
Once a file is picked (and the "Open" button is tapped, if applicable), the file picker should close and go back to the app, providing it with a `FileData` object, if one was selected.

## Actual Behavior
On Chrome OS (not on  Android normal devices, those work fine), the file picker menu starts normally. After a file has been selected and the "Open" button is tapped, the screen only deselects everything and doesn't do anything else.

If the file is picked **again**, and the "Open" button gets tapped **again**, the screen finally closes as intended. But this should happen after **the first time the file is picked**.

Additionally, if the intent gets **closed manually** (by pressing the back button on the window), the rest of our code gets executed, the file gets picked and gets treated by whatever our app does.

## Steps to Reproduce the Problem
This one will be tricky to debug. Our code is literally as easy as:
`FileData fileData = await CrossFilePicker.Current.PickFile();`

You also need to try it out on a Chromebook.

Here is a video of the file picker running on the Chromebook, if that helps - https://youtu.be/_cxlH1rQeqc

## Specifications

  - NuGet package version: **2.1.18**
  - Platform(s): **Chrome OS (running as Android app)**

**Comment by vividos** [comment]
Unfortunately I don't have access to Chrome OS. Could you repruduce the error using the plugin's Sample project (in the GitHub repository)? In your case it's probably best to check if you can debug and fix the problem for yourself. After all, the plugin is open source, and we are happy to accept PRs. Thanks!

**Comment by ivml** [comment]
Thank you for your comment, it makes quite a lot of sense and I would love to do that. If the bug shows up again.

However, in the meantime, we might've found the issue. One thing I tried out was calling the file picker from the main thread:

```
Device.BeginInvokeOnMainThread(async () =>
{
    FileData fileData = await CrossFilePicker.Current.PickFile();

    //handle fileData
});
```

Another thing that changed was a developer option in the settings of the device - we had **Don't keep activities** turned on to make sure our app was restarting properly. It was turned off this morning.

One of the two (or maybe both?) fixed the issue, and we no longer encounter the problem.

Let me know if that makes sense or I should actually investigate further :)

**Comment by vividos** [comment]
Could you verify that the "Don't keep activities" developer flag fixed the problem? My guess is that calling PickFile() in a non-UI thread was the error, but the plugin could handle that potential error condition.

**Comment by vividos** [comment]
@ivml As we didn't hear from you, I consider this issue as solved for now. Thanks for reporting that issue!

**Comment by ivml** [comment]
The "Don't keep activities" dev flag was the culprit. It works as intended without the flag.

Apologies for not responding, I seem to have forgotten that I didn't respond.

**Comment by vividos** [comment]
Thanks!
