### ISSUE TITLE
[Feature Request] Add Date to fileData

### ISSUE THREAD

**Issue by bluekuen** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#146]
It's hard on Android to get the File DateTime.
I tried it with the string i get from google drive for example:

content://com.google.android.apps.docs.storage/document/acc%3D2%3Bdoc%3Dencoded%3DrighArrVG%2FbmPu3iP%2B8eAMUtEMOy%2BWopwMSW4Cu9GaGkVt1u6NpYWJXo7fNxKF%2BZNQ%3D%3D

I didn't find a way to get the correct Date from this FilePath and didn't find a way to do so. 

It would be great if you could add the DateTime as seperate property of the FileData.

Kind Regards,
bluekuen

**Comment by vividos** [comment]
Do you have code to do this on Android? We could surely include this code in the FilePicker if you provide it. Thanks!

**Comment by bluekuen** [comment]
No sadly not, i was looking for a way to do it and opened another issue relevant to this but didn't get an useful answer. That's why i thought you maybe are more into it.

**Comment by vividos** [comment]
I think under Android the only chance with content:// URLs would be to query the content provider for a date column, but I have no experience with that approach.

**Comment by jfversluis** [comment]
Closing this since this project will retire, please check out [Xamarin.Essentials](https://github.com/xamarin/Essentials/tree/main/Xamarin.Essentials/FilePicker) which now has a FilePicker based on this one.
