### ISSUE TITLE
[Feature Request] Use the real FilePath in Android if possible

### ISSUE THREAD

**Issue by kilimnik** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#150]
It would be great if the FilePath would return the real file path and not the logical one. I see you have already a method in the IOUtil.android.cs file, why don't use it?

**Comment by vividos** [comment]
As you probably figured it out, the plugin already calls that method :-)

**Comment by kilimnik** [comment]
Yeah I saw that afterall.
Currently working on a fork, to allow me to get the stream for a file I picked in the past. But I always get errors on compiling. The ResourceDesigner, the SettingDesigner and the Plugin.FilePicker.dll is missing and not generated.

**Comment by vividos** [comment]
I guess you can just delete the designer files and VS will regenerate them.

**Comment by kilimnik** [comment]
No the problem is they are missing here is one of the errors:

> Severity	Code	Description	Project	File	Line	Suppression State
Error	CS2001	Source file 'C:\Users\Daniel\source\repos\FilePicker-Plugin-for-Xamarin-and-Windows\src\Plugin.FilePicker\obj\Debug\MonoAndroid80\Resource.Designer.cs' could not be found.	Plugin.FilePicker (netstandard1.0)	C:\Users\Daniel\source\repos\FilePicker-Plugin-for-Xamarin-and-Windows\src\Plugin.FilePicker\CSC	1	Active
