### ISSUE TITLE
IOS: Why does FileData.FileName add ".dat" extension when we select any file without extension?

### ISSUE THREAD

**Issue by muffadal53** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#152]
In IOS, when we select any file without extension the FileData.FileName contains ".dat" extension along with filename e.g. "1.dat"? Is this default behavior when we select any file without extension?

## Specifications

  - NuGet package version: 2.1.18
  - Platform(s): IOS 13

**Comment by jfversluis** [comment]
Closing this since this project will retire, please check out [Xamarin.Essentials](https://github.com/xamarin/Essentials/tree/main/Xamarin.Essentials/FilePicker) which now has a FilePicker based on this one.
