### ISSUE TITLE
Plugin not Working with wpf (.Net Core 3.0)

### ISSUE THREAD

**Issue by zaratul77** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#153]
## Expected Behavior

Selecting File without exception

## Actual Behavior

Exception when calling 
var filePicker = await CrossFilePicker.Current.PickFile();

Ex: 
System.NotImplementedException
  HResult=0x80004001
  Message=This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.
  Source=Plugin.FilePicker
  StackTrace:
   at Plugin.FilePicker.CrossFilePicker.get_Current()
   at OnObject.ImportPage.<SelectUploadButton_Clicked>d__10.MoveNext() 

## Steps to Reproduce the Problem

  1. Add Wpf Core 3.0 Project to your xamarin app
  1. Open Filepicker
  

## Specifications

  - NuGet package version: 2.1.34
  - Platform(s): Windows 10

**Comment by vividos** [comment]
It seems the plugin doesn't support WPF in .NET Core yet. My guess is because of this it gets the. NET Standard assembly instead.
