### ISSUE TITLE
Add TakePersistableUriPermission

### ISSUE THREAD

**Issue by Mike134** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#158]
Would like for the FilePicker in Android to persist permissions after a file has been successfully selected.

I'm wondering if in FilePickerActivity.android.cs, in OnActivityResult at around line 153 adding something similar to the following would do the trick.
```
if (Build.VERSION.SdkInt >= Android.OS.BuildVersionCodes.Kitkat)                
{
    context.ContentResolver.TakePersistableUriPermission(uUri, ActivityFlags.GrantWriteUriPermission | ActivityFlags.GrantReadUriPermission);
}
```

**Comment by vividos** [comment]
I tried to put this in the FilePicker, but calling TakePersistableUriPermission() throws a `SecurityException`...

**Comment by vividos** [comment]
@Mike134 figured it out; see PR #178. Could you test with the latest FilePicker NuGet, 2.1.41-beta, if the error that you found is fixed? Thanks!

**Comment by vividos** [comment]
calling TakePersistableUriPermisssion is now in since some time. I'm closing this issue.
