### ISSUE TITLE
IOS: When we turn off internet connection while we are in FilePicker plugin and now if we select a file nothing happens.

### ISSUE THREAD

**Issue by muffadal53** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#159]
IOS: When we turn off internet connection while we are in FilePicker plugin and now if we select a file nothing happens. Not sure why this happens.
The **CrossFilePicker.Current.PickFile** call should return something. But, it doesn't return from this API call. Can you kindly let me know why this could happen?

## Specifications

NuGet package version: 2.1.18
Platform(s): IOS 13

**Comment by jfversluis** [comment]
Closing this since this project will retire, please check out [Xamarin.Essentials](https://github.com/xamarin/Essentials/tree/main/Xamarin.Essentials/FilePicker) which now has a FilePicker based on this one.
