### ISSUE TITLE
Can't pick files from external storage (SD Card)

### ISSUE THREAD

**Issue by Wawingi** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#160]
I have all configured at my Manifest and file_paths, is working wellwhen im picking a files from internal storage, but when i choose some file in the SD Card is not working and return bugs.

![image](https://user-images.githubusercontent.com/37840665/70415009-f9972600-1a5b-11ea-8d28-4cffc2374833.png)

**Comment by vividos** [comment]
The FileUri that is returned by picking in most cases is not a file path, but an Uri. You have to either access the data by using GetStream() or by copying the stream locally, e.g. in your cache folder.

**Comment by Wawingi** [comment]
if (fileData != null) {
                    var fileName = Path.GetFileName(fileData.FileName);
                    var fileExtensao = Path.GetExtension(fileNome);
                    float fileSize = fileData.DataArray.Length;
                    fileSize = fileSize / 1024;

                    Caminho = fileData.FilePath;

                    Format = fileExtensao.ToUpper();

                    if (Format == ".PDF" || Format == ".PNG" || Format == ".JPG")
                    {}
}


Here is my function, is working good if i pick a file from internal storage, but when i pick from SD card my variable Caminho looks empty.

**Comment by Wawingi** [comment]
if (fileData != null) {
                    var fileName = Path.GetFileName(fileData.FileName);
                    var fileExtensao = Path.GetExtension(fileNome);
                    float fileSize = fileData.DataArray.Length;
                    fileSize = fileSize / 1024;

                    Caminho = fileData.FilePath;

                    Format = fileExtensao.ToUpper();

                    if (Format == ".PDF" || Format == ".PNG" || Format == ".JPG")
                    {}
}


Here is my function, is working good if i pick a file from internal storage, but when i pick from SD card my variable Caminho looks empty.

**Comment by vividos** [comment]
fileData.FileName only contains the file name, not a path. It's only there to check the file extension, as you do. FilePath may contain a content:// URL that you can only access using the Android Content resolver class. Or you use the fileData.GetStream() to get a platform independent Stream object.

**Comment by Wawingi** [comment]
Thanks... i just solve it.

**Comment by vividos** [comment]
I'm closing the ticket then. Thanks!
