### ISSUE TITLE
Compatiblity with WASM (WebAssembly)

### ISSUE THREAD

**Issue by SuperJMN** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#162]
Due to the rise of [Uno Platform](https://platform.uno/), it would be awesome that the FilePicker would be compatible with WASM.

It's a very important feature (https://github.com/unoplatform/uno/issues/508)

**Comment by vividos** [comment]
What would it take to port a file requester to web assembly? I'm not familiar with that. Can any platform dependent API be used?

**Comment by jfversluis** [comment]
Closing this since this project will retire, please check out [Xamarin.Essentials](https://github.com/xamarin/Essentials/tree/main/Xamarin.Essentials/FilePicker) which now has a FilePicker based on this one.
