### ISSUE TITLE
SHOW ONLY PDF FILES

### ISSUE THREAD

**Issue by Wawingi** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#163]
hi, i've my method to pickfile:

 private async void Anexar(){
               **fileData = await CrossFilePicker.Current.PickFile();**

       ......... another code
}

<img width="226" alt="Capturar" src="https://user-images.githubusercontent.com/37840665/71521878-cd383200-28c2-11ea-8ce0-971006503971.PNG">
 when i click at de anexar button it open a folder with all kind of files:

<img width="230" alt="Capturar" src="https://user-images.githubusercontent.com/37840665/71521945-04a6de80-28c3-11ea-8ca2-608446d1f8bc.PNG">

but i want to see only a pdf files in that folder. Cause here i'm seeng another files...

**Comment by vividos** [comment]
You have to specify the file type that you want the file picker to use. See the readme.md file in the GitHub repository, and there's also sample code how to do it.

**Comment by Wawingi** [comment]
it worked for me...

private async void Anexar(){
      string[] allowedTypes = { "application/pdf","image/*"};
      fileData = await CrossFilePicker.Current.PickFile(allowedTypes );
}

**Comment by Wawingi** [comment]
it worked for me...

private async void Anexar(){
string[] allowedTypes = { "application/pdf","image/*"};
fileData = await CrossFilePicker.Current.PickFile(allowedTypes );
}
