### ISSUE TITLE
How to Keep Orientation set to landscape when browsing for files?

### ISSUE THREAD

**Issue by premingiet** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#164]
## Expected Behavior
when on android main activity, if screen orientation is set to landscape,  when browsing files, screen orientation should be landscape too.

## Actual Behavior
In android main activity, if screen orientation is set to landscape,  when browsing files, screen orientation automatically changes to portrait.

## Steps to Reproduce the Problem

  1. set ScreenOrientation = ScreenOrientation.Landscape in android main activity and try to browse the files.

## Specifications

  - NuGet package version: 2.1.34
  - Platform(s): Android 8.1

**Comment by vividos** [comment]
This is a new feature request. If you happen to have some time, we happily accept PRs. Best way would probably be to add a new PickFile method that takes a new PickOptions object that has an Orientation parameter. Or alternatively, on Android, try to get the orientations from the parent Activity and apply those to the FilePickerActivity. Might be easier to implement.

**Comment by jfversluis** [comment]
Closing this since this project will retire, please check out [Xamarin.Essentials](https://github.com/xamarin/Essentials/tree/main/Xamarin.Essentials/FilePicker) which now has a FilePicker based on this one.
