### ISSUE TITLE
Plugin not working : iOS 13 App

### ISSUE THREAD

**Issue by OladotunO** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#165]
## Expected Behavior
User should see the picker and be able to pick a file

## Actual Behavior
The code stops at step one
 FileData fileData = await CrossFilePicker.Current.PickFile();

There is no error report or stack trace, the app freezes

## Steps to Reproduce the Problem
My Code
```
 public class MyDocPickerPlugin
    { 
        public async Task<List<string>> GetFileInfo()
        {
            List<string> FileInfo= new List<string>();
            //###################

            try
            {
                **FileData fileData = await CrossFilePicker.Current.PickFile();**
                if (fileData == null)
                    return FileInfo ; // user canceled file picking

                string fileName = fileData.FileName;
                string contents = System.Text.Encoding.UTF8.GetString(fileData.DataArray);

                System.Console.WriteLine("File name chosen: " + fileName);
                System.Console.WriteLine("File data: " + contents);

                FileInfo.Add(fileName);
                FileInfo.Add(contents);
            }
            catch (Exception ex)
            {
                System.Console.WriteLine("Exception choosing file: " + ex.ToString());
            }

            //###################
            return FileInfo;
        }
        }
}
```

  1.
  1.
  1.

## Specifications

  - NuGet package version: 2.1.34
  - Platform(s): Iphone 7, ios7 , Xamarin.ios

**Comment by vividos** [comment]
Could you also reproduce this behavior with the sample app in this repository? Is there log output in the visual studio debug window? Or in the macOS Console app?

**Comment by OladotunO** [comment]
Hi Vividos, I got it to work by adapting the sample macOs code for iPhone xamarin.IOS.
For what is worth, use of a method that returns a value like  I tried above fails, but a void method works.

Cheers

**Comment by vividos** [comment]
Thanks for the feedback!
