### ISSUE TITLE
Tizen support

### ISSUE THREAD

**Issue by VladislavAntonyuk** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#166]
Since Xamarin.Forms supports Tizen, it would be nice if the plugin also supported it.

**Comment by jfversluis** [comment]
Closing this since this project will retire, please check out [Xamarin.Essentials](https://github.com/xamarin/Essentials/tree/main/Xamarin.Essentials/FilePicker) which now has a FilePicker based on this one.
