### ISSUE TITLE
FolderPicker

### ISSUE THREAD

**Issue by VladislavAntonyuk** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#169]
It would be nice to extend the plugin with PickFolder method.
Possible use cases:
- Select a folder to search files (folder with images, music, etc)
- Select a folder to save file

**Comment by vividos** [comment]
Well, as a Xamarin plugins user I would not expect to find a FolderPicker method in a FilePicker plugin, but YMMV. There is a PR already for a folder picker, but I think it would better fit in another plugin, or even in Xamarin.Essentials. Just my two cents...

**Comment by VladislavAntonyuk** [comment]
We can rename plugin to FileFolderPicker or something similar

**Comment by jfversluis** [comment]
In theory that is possible, but I think we’re going to make a lot of people unhappy if we start renaming namespaces.

The future of this plugin is with Essentials. For the time being this won’t be implemented because of that. Sorry :(

**Comment by VladislavAntonyuk** [comment]
I am sure we do not need to rename namespaces (even the name of the package).
Unfortunately Essentials doesn't support Xamarin.Mac, WPF etc(
