### ISSUE TITLE
DataArray giving empty byte array

### ISSUE THREAD

**Issue by Altaf07Latheef** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#17]
Whenever selecting file in android i am getting empty byte array for DataArray ,i dint test iOS. Also i cant find GetStream() function .

**Comment by jfversluis** [comment]
Which Version did you use?

**Comment by Altaf07Latheef** [comment]
its 1.2.1

**Comment by jfversluis** [comment]
Please have a look at the last [beta package](https://www.nuget.org/packages/Xamarin.Plugin.FilePicker/1.4.34-beta) and see if the issue is still current.

**Comment by Altaf07Latheef** [comment]
yea in that version GetStream() is there, but for DataArray same empty thing happening.
   var fileData = await CrossFilePicker.Current.PickFile();
                  int count = fileData.DataArray.Length;
count is 0

**Comment by jfversluis** [comment]
Would you be able to create a quick reproduction project? That would really help :)

Also which version of Android are you using? Phone or emulator? Which phone?

**Comment by Altaf07Latheef** [comment]
Actually i am using the above mentioned code only in a new project because i need a filepicker that works well. Running in Android version 6.0 htc one phone

**Comment by Altaf07Latheef** [comment]
When i tried to run from ios simulator the following exception came,

System.NotImplementedException: This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

even when i installed the nuget in ios.

**Comment by jfversluis** [comment]
Thanks for you issue! This does sound like it is using the shared lib which shouldn't happen. Please ensure yourself that the library is indeed added to the iOS project and clean and rebuild the project.

**Comment by javierescobare** [comment]
I have the same problem right now

**Comment by jfversluis** [comment]
What problem exactly? This issue seems to describe multiple now :)

**Comment by Altaf07Latheef** [comment]
@jfversluis i have done the way you told but its showing the same exception in iOS .

**Comment by javierescobare** [comment]
On Android:
I had the "empty byte array" problem first, but now: 
https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/issues/18.

On iOS:
I'm having System.NotImplementedException, as mentioned above. Clean and Rebuild didn't work.

**Comment by jfversluis** [comment]
@Altaf07Latheef @javieresc97 The iOS issue should be resolved in the latest beta package. Since this issue describes multiple things now, I will be closing this one.

If the original problem is still occurring, please open a new issue.
