### ISSUE TITLE
App is Closing after selecting file

### ISSUE THREAD

**Issue by ghost** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#170]
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - NuGet package version:
  - Platform(s):

**Comment by jfversluis** [comment]
I’m very sorry but without any additional information as requested by the template we are not able to help you. 

Please provide details about the device/emulator used, relevant code and a stracktrace/error message.
