### ISSUE TITLE
Android Intent Action Crash

### ISSUE THREAD

**Issue by championofblocks** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#172]
## Expected Behavior
The file picker should not crash on Android devices when picking a file.

## Actual Behavior
Some Android devices will crash when attempting to launch the picker with `Intent.ActionGetContent` and `Intent.ActionOpenDocument` works more consistently in our findings.

The crash is:
`java.lang.SecurityException: Permission Denial: opening provider com.google.android.apps.docs.storagebackend.StorageBackendContentProvider from ProcessRecord{c8decebd0 6909:<package_name>/u0a206} (pid=6909, uid=10206) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs`

## Steps to Reproduce the Problem
We're unsure at the moment if this is device specific, or related to the setup of the documents browser on the Android device itself. So far we have only witnessed this crash on a Samsung S5E (SM-T720) Tablet running Android 9

  1. Create an Android app
  2. Call `Task<FileData> PickFile(string[] allowedTypes = null)` from an `async/await` routine
  3. Select a file from the picker
  4. App crashes with full stack trace below

```
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.34(intptr,intptr)
java.lang.SecurityException: Permission Denial: opening provider com.google.android.apps.docs.storagebackend.StorageBackendContentProvider from ProcessRecord{c8decebd0 6909:com.tyco.illustra_tools/u0a206} (pid=6909, uid=10206) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
android.os.Parcel.createException Parcel.java:1966
android.os.Parcel.readException Parcel.java:1934
android.os.Parcel.readException Parcel.java:1884
android.app.IActivityManager$Stub$Proxy.getContentProvider IActivityManager.java:4039
android.app.ActivityThread.acquireProvider ActivityThread.java:6351
android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider ContextImpl.java:2825
android.content.ContentResolver.acquireUnstableProvider ContentResolver.java:1835
android.content.ContentResolver.openTypedAssetFileDescriptor ContentResolver.java:1449
android.content.ContentResolver.openAssetFileDescriptor ContentResolver.java:1302
android.content.ContentResolver.openInputStream ContentResolver.java:1022
mono.java.lang.RunnableImplementor.n_run(Native Method)
mono.java.lang.RunnableImplementor.run(Unknown Source:0)
android.os.Handler.handleCallback Handler.java:873
android.os.Handler.dispatchMessage Handler.java:99
android.os.Looper.loop Looper.java:214
android.app.ActivityThread.main ActivityThread.java:7080
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:494
com.android.internal.os.ZygoteInit.main ZygoteInit.java:965
Caused by: android.os.RemoteException: Remote stack trace:
com.android.server.am.ActivityManagerService.getContentProviderImpl ActivityManagerService.java:15638
com.android.server.am.ActivityManagerService.getContentProviderImpl ActivityManagerService.java:15547
com.android.server.am.ActivityManagerService.getContentProvider ActivityManagerService.java:16112
android.app.IActivityManager$Stub.onTransact$getContentProvider$ IActivityManager.java:11035
android.app.IActivityManager$Stub.onTransact IActivityManager.java:295
```

## Specifications

  - NuGet package version: 2.1.34
  - Platform(s): Xamarin Native (Android)

**Comment by vividos** [comment]
I think you're getting the exception because you're doing something like this:
https://stackoverflow.com/questions/48187647/exception-java-lang-securityexception-reading-mediadocumentsprovider-requ#48188753
Also a good read, linked in that answer:
https://commonsware.com/blog/2016/08/10/uri-access-lifetime-shorter-than-you-might-think.html

**Comment by championofblocks** [comment]
@vividos yeah I agree, this describes the likely cause of failure. in our case, the files can be in the order of ~80mb and we're uploading them to a RESTful web service once the user has picked a file, so we access to the file to persist past the picking context.  there's no indication in this library that our use case would fail though and, across almost all of our test devices, everything works fine.

for the very few instances where this is an issue however, we would like to have a solution. currently the library doesn't offer a way to override the default action of the intent. other developers might find that the default action works fine so rather than change it entirely, it would be good to open it out for overriding where appropriate. arguably the library could be more flexible.

**Comment by vividos** [comment]
You could immediately call GetStream(), it could be that once the stream is open, the file won't go away.

**Comment by championofblocks** [comment]
It's possible yeah. Is there any reason for not making the library more flexible though?

**Comment by vividos** [comment]
No special reason except that it didn't occur to me or @jfversluis yet. There's discussion in #173 about how to fix that behavior. Maybe using ACTION_OPEN_DOCUMENT from a specific API version on and calling TakePersistableUriPermissions() is the way to go. If you have time to try to fix that, feel free to put a PR together. Thanks!

**Comment by championofblocks** [comment]
PR #173 is my attempt to add some flexibility to the library, to help developers avoid the crash I experienced. If you prefer to avoid flexibility and just hardcode the intent action, that would probably fix the issue too, but doesn't add the flexibility. I'm happy either way. If you prefer the hardcoded option I can close that PR and provide a new one with the suggested implementation

**Comment by vividos** [comment]
@championofblocks Could you test with the latest FilePicker NuGet, 2.1.41-beta, if the error that you found is fixed? Thanks!

**Comment by championofblocks** [comment]
Sure thing @vividos, we'll test this ASAP. Thanks for adding this.

**Comment by vividos** [comment]
You're welcome!
