### ISSUE TITLE
System.UnauthorizedAccessException: Access to the path "...." is denied when getting the stream of some files on Android

### ISSUE THREAD

**Issue by ingweland** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#184]
## Expected Behavior
Should be able to use any file on Android

## Actual Behavior

Files with such problem can reside in different directories. Some files might work others might not in the same directory.

```
03-25 12:26:02.039 E/mono-rt ( 1937): System.UnauthorizedAccessException: Access to the path "/storage/emulated/0/Download/leroy.txt" is denied.
03-25 12:26:02.039 E/mono-rt ( 1937):   at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x001aa] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mcs/class/corlib/System.IO/FileStream.cs:239 
03-25 12:26:02.039 E/mono-rt ( 1937):   at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mcs/class/corlib/System.IO/FileStream.cs:91 
03-25 12:26:02.039 E/mono-rt ( 1937):   at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
03-25 12:26:02.039 E/mono-rt ( 1937):   at System.IO.File.OpenRead (System.String path) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/external/corefx/src/System.IO.FileSystem/src/System/IO/File.cs:266 
03-25 12:26:02.039 E/mono-rt ( 1937):   at Plugin.FilePicker.FilePickerImplementation+<>c__DisplayClass5_1.<PickFileAsync>b__2 () [0x00034] in D:\a\1\s\src\Plugin.FilePicker\Android\FilePickerImplementation.android.cs:114 
03-25 12:26:02.039 E/mono-rt ( 1937):   at Plugin.FilePicker.Abstractions.FileData.GetStream () [0x0000f] in D:\a\1\s\src\Plugin.FilePicker\FileData.shared.cs:156 
```

## Steps to Reproduce the Problem

  1. Pick the file
  2. Call GetStream on FileData
  

## Specifications

  - NuGet package version: 2.1.41-beta
  - Platform(s): Xamarin.Forms 4.5; Android 10

## Discussion

It looks like this issue happens when target SDK is Android 10. Tested on the device with Android 10 as well (not sure about devices with lower version).
It might be related to newly introduced Scoped storage.
Few resources which might be helpful:
https://github.com/xamarin/xamarin-android/issues/3426#issuecomment-579045662
https://www.youtube.com/watch?v=UnJ3amzJM94
I noticed that this exception happens when we find a local Uri (and not just using content Uri) https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/blob/8e1813cb55440a1e542d3c1437a183a4f326451e/src/Plugin.FilePicker/Android/FilePickerActivity.android.cs#L168
and then are using 
https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/blob/8e1813cb55440a1e542d3c1437a183a4f326451e/src/Plugin.FilePicker/Android/FilePickerImplementation.android.cs#L114
instead of 
https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/blob/8e1813cb55440a1e542d3c1437a183a4f326451e/src/Plugin.FilePicker/Android/FilePickerImplementation.android.cs#L110

Why should we use local paths at all? Can we always use `content` Uri and `OpenInputStream`?

## Quick fix
Add `android:requestLegacyExternalStorage="true"` to `application` tag in manifest

**Comment by vividos** [comment]
The whole code to try to resolve a content:// URI to a file path was there from the beginning. My guess is that FilePicker users insisted on getting a file path on the picked file, even when it goes against Android's model. Maybe we should skip those efforts when running on Android 10 and above. We are happy to accept any PR that you can come up for us. Thanks!

**Comment by manjeetmalik10** [comment]
Thanks Great its(android:requestLegacyExternalStorage="true") working for me as well in android 10

**Comment by aharwood2** [comment]
Can confirm the same issue and the quick fix suggest also works for me.

**Comment by inimirpaz** [comment]
Please be aware that:

> Caution: After you update your app to target Android 11 (API level 30), the system ignores the requestLegacyExternalStorage attribute when your app is running on Android 11 devices, so your app must be ready to support scoped storage and to migrate app data for users on those devices.

See [here](https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage).

We urge a fix in the plugin code I guess. And I guess it all boils down to GetExternalStoragepublicDirectory being deprecated in Android Q.

**Comment by vividos** [comment]
We always welcome patches and pull requests! So of you are able to come up with a fix, just propose it. Thanks!

**Comment by jlucaspains** [comment]
I just proposed a fix via PR. I was able to test it in my own project and it works fine. The change is simple, maybe too simple even. I'm happy to make adjustments if needed.
