### ISSUE TITLE
Not working on Windows 10 IoT Core

### ISSUE THREAD

**Issue by MACsrl** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#186]
## Expected Behavior
Open a dialog to explore file.

## Actual Behavior
await CrossFilePicker.Current.PickFile() instantly return null value (it's working on uwp runned on regoular windows)

## Steps to Reproduce the Problem

  1. just run "await CrossFilePicker.Current.PickFile()" from a windows 10 iot device

## Specifications

  - NuGet package version: 2.1.34
  - Platform(s): Windows 10 IoT Core

**Comment by vividos** [comment]
Can you reproduce it with the Sample project in this repository? Can you step into the `PickFile()`code to see what goes wrong? Maybe there is an API that's unavailable on IoT devices?

**Comment by MACsrl** [comment]
hi vividos, iam unable to step into PickFile funtion, or maybe i dont know how to...
this is the code i run:

var filePicked = await CrossFilePicker.Current.PickFile();
if (filePicked == null)
        return;

the PickFile function exits instantly, and filePicked get null.
maybe window 10 IoT doesnt have a default file explorer to open?

**Comment by vividos** [comment]
Please use the sample project, then stepping in should work, as it doesn't use the NuGet package. Thanks!

**Comment by MACsrl** [comment]
iam trying to run the sample project in my pc before testing it on the iot device, but i get tons of error, all cos of using not recognized:

using Windows.Storage;
using Windows.Storage.AccessCache;
using Windows.System;
