### ISSUE TITLE
As a cross platform developer, I want the same behavior for all platforms

### ISSUE THREAD

**Issue by de-wolff** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#189]
## Expected Behavior

On all platform I want to be able to use 
`FileData fileData = await CrossFilePicker.Current.PickFile( new string[] { "*.json" });
`
## Actual Behavior
On windows I have to use
`FileData fileData = await CrossFilePicker.Current.PickFile( new string[] { "Jsontype (*.json)|*.json" });
`On uwp I have to use
`FileData fileData = await CrossFilePicker.Current.PickFile( new string[] { "*.json" });
`
On anroid I have to use
`FileData fileData = await CrossFilePicker.Current.PickFile( new string[] { "text/json" });
`
On IOs I have to use
`FileData fileData = await CrossFilePicker.Current.PickFile( new string[] { UTType.JSON });
`

**Comment by jfversluis** [comment]
Closing this since this project will retire, please check out [Xamarin.Essentials](https://github.com/xamarin/Essentials/tree/main/Xamarin.Essentials/FilePicker) which now has a FilePicker based on this one.
