### ISSUE TITLE
Getting error as exposed beyond app through Intent.getData()

### ISSUE THREAD

**Issue by shubhambhosale** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#191]
Hi, 
I am getting an exception as "file:///data/user/0/com.test.TestApp/files/.local/share/Attachments/test.xlsxTesttSiS079UgyNhBihMJhiXsQuLrYIbeR6614gKk7HB5TJqISxij+VIiS+zX6xFgrzAipJdv5AmPsdykBhIjuCVNd3qq3SUdUrf2kda/Uma4ms= exposed beyond app through Intent.getData()".  

I am not sure what causing the issue.

Please let me know if I am missing something.

## Specifications

  - NuGet package version: 2.1.34
  - Platform: Android

**Comment by vividos** [comment]
I guess you tested with the newer NuGet package 2.1.41, where this works?
