### ISSUE TITLE
Image does not show when selected from SDcard

### ISSUE THREAD

**Issue by Guervyl** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#192]
## Expected Behavior
I want to show the stream image in an Image tag

## Actual Behavior
The image does not show when pick from Sdcard.

## Steps to Reproduce the Problem

  1. FileData fileData = await CrossFilePicker.Current.PickFile(new string[] { "image/png", "image/jpeg" });
  2. img.Source = ImageSource.FromStream(() =>
                {
                    return imageProduct.FileData.GetStream();
                });

## Specifications
I copy the same image into the sdcard and into the phone. I select the image from the internal storage, Image tag shows the image. But, when I select the image from the sdcard, the image does not show up.

  - NuGet package version: 2.1.34
  - Platform(s): Android

**Comment by vividos** [comment]
@Guervyl what was the solution in the end? Might want to share?
