### ISSUE TITLE
Nugget execute commands in class library project

### ISSUE THREAD

**Issue by tuke307** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#193]
## Expected Behavior
Project should execute the command in the application project(.net core) but want to execute in the class library(.net framework).

## Actual Behavior
System.NotImplementedException: 'This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.'

## Steps to Reproduce the Problem

  1. Create .net standard 2.0 project (with basic view-model code)
  2. Create .net framework 4.6.1 class library project (with WPF-specific view models and the nugget commands)
  3. Create .net core 3.0 WPF application project (with views)
  4. Install Nugget on every project and reference each project

## Specifications

  - NuGet package version: 2.1.41
  - Platform(s): Windows (WPF)

**Comment by vividos** [comment]
Support for .NET Core was only recently added and is only available in the latest beta NuGet, I believe. Could you test that please? Thanks

**Comment by tuke307** [comment]
yes, it works fine with the newest beta.

**Comment by vividos** [comment]
Thanks for checking. I'm closing the ticket then.
