### ISSUE TITLE
Lack of IOS real file path.

### ISSUE THREAD

**Issue by skowront** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#194]
## Expected Behavior
There should be another prop for the REAL path on IOS. The temporary one is useless if you want to use the file later, or save data to it.

## Actual Behavior
As menstioned in troubleshooting.
Picked file path is invalid, file doesn't exist

On iOS the plugin uses UIDocumentPickerViewController and specifies the mode UIDocumentPickerMode.Import. After picking is done, iOS copies the picked file to the app's temporary "Inbox" folder where it can be accessed. iOS also cleans up the temporary inbox folder regularly. After picking the file you have to either copy the file to another folder, access the data by getting the property DataArray or opening a stream to the file by calling GetStream().

## Specifications

  - NuGet package version: 2.1.43-beta 
  - Platform(s): IOS

**Comment by vividos** [comment]
Changing the UIDocumentPickerMode may be the solution. Can you come up with a PR? We'd love to integrate that. Thanks!

**Comment by skowront** [comment]
> Changing the UIDocumentPickerMode may be the solution. Can you come up with a PR? We'd love to integrate that. Thanks!

Indeed. "Open" mode instead of "Import" solves the problem. 

I would change this and nothing more:
https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/blob/696bcc1b21c2049799420542bf4e143854ffcf35/src/Plugin.FilePicker/FilePickerImplementation.ios.cs#L156


to 


            var documentPicker = new UIDocumentPickerViewController(allowedUtis, UIDocumentPickerMode.Open);

PERSONAL OPINION
Personally I'd go for "always open" solution, when you are allowed to keep the original path, you may always create a temp file on your own, as you would do on Android, but when you are given the temp path that implies you are stuck with the temp path.

I saw this note in your code.
"
   // NOTE: Importing (UIDocumentPickerMode.Import) makes a local copy of the document,
            // while opening (UIDocumentPickerMode.Open) opens the document directly. We do the
            // first, so the user has to read the file immediately.
"
I believe most the most obvious usage is 1.get the file, 2.analyze/modify data and 3.save to that exact file, so an opposite approach would be more appropriate and logical ("leave open in code and a note that says: change to export if you want to read immediately").  

I'd be glad to make a PR later, but I guess you should reconsider that argumnentation from the "note" in the code anyways.

**Comment by vividos** [comment]
Well the exact use case can differ. In my app for example, I just want to select and load .KML files and never save back to that file again.

That code was there from the beginning, I just documented why it is used that way. I think it's time to change the mode that is used.

**Comment by jfversluis** [comment]
Closing this since this project will retire, please check out [Xamarin.Essentials](https://github.com/xamarin/Essentials/tree/main/Xamarin.Essentials/FilePicker) which now has a FilePicker based on this one.
