### ISSUE TITLE
Carsh on cancel on iOS because tcs is null

### ISSUE THREAD

**Issue by softlion** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#196]
## Expected Behavior
don't crash on cancel

## Actual Behavior
crash on cancel in tcs.SetResult(null); because tcs is null.
I have not determined the conditions that leads to this problem.
But it just happened while debugging on a xr device.

```
   public void DocumentPicker_WasCancelled(object sender, EventArgs args)
        {
            var tcs = Interlocked.Exchange(ref this.completionSource, null);
            tcs.SetResult(null);
        }
```

## Specifications

  - NuGet package version: 2.1.41
  - Platform(s): iOS 13

**Comment by jfversluis** [comment]
Closing this since this project will retire, please check out [Xamarin.Essentials](https://github.com/xamarin/Essentials/tree/main/Xamarin.Essentials/FilePicker) which now has a FilePicker based on this one.
