### ISSUE TITLE
Pick file with specific file extension android

### ISSUE THREAD

**Issue by graysuit** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#198]
@vividos  @jfversluis 
## Expected Behavior
**I want to open files with specific file extension filter.**

## Actual Behavior
Lets suppose I have file named **"abc.ext"**, So I want to filter all files with that specific extension i.e .**ext**.
Currently I seen android is supporting only **MIME types** not extension. Is that so ?
This not working.
```Csharp
var fileTypes = new string[] { "ext/*" }; 
FileData fileData = await CrossFilePicker.Current.PickFile(fileTypes);
```

## Specifications

  - NuGet package version:Latest until now
  - Platform(s):Android

**Comment by vividos** [comment]
Unfortunately Android lets you only specify MIME types to filter the selectable files (the others are grayed out and unselectable). If you know the MIME type, that's good, but in other cases you should check the FileName property and its file extension if it's an acceptable one.

**Comment by graysuit** [comment]
@vividos 
Yes I want that other files with filters other than **".ext"** should be garyed out.
So is there any workaround for that problem that android accept only accept MIME type ?
Or any other method ? My files are basically binary and encrypted files, So it may not have have a well MIME type.
If not I am fine to choose onlye specific file extension after selection in my code.

**Comment by vividos** [comment]
You could check the Android docs if there is a way, but I doubt it. In my app I let the user pick any file and notify the user when parsing fails.
