### ISSUE TITLE
**Java.Lang.RuntimeException:** 'Canvas: trying to draw too large(192000000bytes) bitmap.'

### ISSUE THREAD

**Issue by markshiffa** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#199]
i have got this when trying to browse camera folder or opening a photo with modern smartphone on Android.

08-27 17:07:13.631 I/Choreographer( 1146): Skipped 100 frames!  The application may be doing too much work on its main thread.
**Java.Lang.RuntimeException:** 'Canvas: trying to draw too large(192000000bytes) bitmap.'

**Comment by jfversluis** [comment]
I don't think this has to do with the picker. You're trying to open a 100+ MB image. You probably want a different way of doing that.

**Comment by markshiffa** [comment]
ok! i figured it out... the picker shows and process also dng pictures (raw images). is there any way to exclude dng?

UPDATE:
is not only related to dng files,
if i try to open a jpg of 14MB it fires this error too.
I think it's related to the resolution of the image.

**Comment by markshiffa** [comment]
i'm sorry, is not your culprit.
it was me trying to put a big image in a small image tag after picking it with your picker, so te issue is mine!
i try to resolve it by copying in temp folder and then resizing
