### ISSUE TITLE
When calling PickFile unexpected apps are included as the source starting in Android API 29

### ISSUE THREAD

**Issue by jamesjlang** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#200]
## Expected Behavior
In a Xamarin.Android project when PickFile is called, the user should be immediately presented with the file picker. The "Open From" option in the hamburger menu should include all file sources (Dropbox, other apps).

## Actual Behavior
When PickFile is called, the user is presented with a selection of what app to use (Files is there but then random other options for example Podcast apps). When the files app is selected, not all sources are included in the "Open From" menu (Dropbox being the most notably absent). 

This started immediately after we changed our Target Android version to API level 29. Prior everything was working as in the Expected Behavior section

## Specifications
  - NuGet package version: v2.1.41
  - Platform(s): Xamarin Android 10.0 API 29

**Comment by vividos** [comment]
Do you have a screenshot of that behavior?

**Comment by brainseed** [comment]
![screenshot_20200828-104310](https://user-images.githubusercontent.com/15362105/91580995-e5fa5b00-e91b-11ea-9942-3d3238f1cd9a.png)

![screenshot_20200828-104339_2](https://user-images.githubusercontent.com/15362105/91581030-ef83c300-e91b-11ea-8086-528a7acaab9e.png)

**Comment by jamesjlang** [comment]
![screenshot_20200828-104310](https://user-images.githubusercontent.com/15362105/91581138-13470900-e91c-11ea-843e-b8302025ebdd.png)
Here is the shot of what I see when I call PickFile

![screenshot_20200828-104339_2](https://user-images.githubusercontent.com/15362105/91581159-19d58080-e91c-11ea-86f5-47217d959b22.png)
Here is what I see in the resulting file selection activity when I select Files

If it is helpful, this is the exact line of code I am using to call out to the Filepicker in a Xamarin Android Fragment:
using (FileData fileData = await CrossFilePicker.Current.PickFile(new string[] { "image/jpg", "image/jpeg", "image/png" })) {

**Comment by vividos** [comment]
It seems you have two apps on your phone that answer to the ACTION_OPEN_DOCUMENT intent. What is "Pocket Ca..."? My guess is that when you uninstall that app, the first screenshot doesn't appear anymore. I don't know how to control what "app" is called to pick a file, though...

**Comment by jamesjlang** [comment]
It's a podcast app which doesn't make sense. The issue I'm reporting however is that this behavior changed upgrading my API version to 29.

If I install a build that was compiled against an earlier API version it works as expected.

**Comment by jfversluis** [comment]
Closing this since this project will retire, please check out [Xamarin.Essentials](https://github.com/xamarin/Essentials/tree/main/Xamarin.Essentials/FilePicker) which now has a FilePicker based on this one.
