### ISSUE TITLE
System.UnauthorizedAccessException: Access to the path "/"

### ISSUE THREAD

**Issue by michelsiqueiraf** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#201]
![1](https://user-images.githubusercontent.com/40748467/91506319-38019900-e8a8-11ea-938f-e149e6339918.png)

![2](https://user-images.githubusercontent.com/40748467/91506329-3f28a700-e8a8-11ea-9eb3-e4d9c68eb57b.png)

![3](https://user-images.githubusercontent.com/40748467/91506335-42bc2e00-e8a8-11ea-9277-79965ff72a02.png)

![4](https://user-images.githubusercontent.com/40748467/91506344-4780e200-e8a8-11ea-8295-c1ce42e1dd9f.png)

![5](https://user-images.githubusercontent.com/40748467/91506355-4bacff80-e8a8-11ea-8fcf-f844c54fe11a.png)

## Specifications

  - NuGet package version: 2.1.41
  - Platform(s): Android

**Comment by michelsiqueiraf** [comment]
updated to version 3.2.0 solved the problem.

**Comment by FIELDPOINT** [comment]
> updated to version 3.2.0 solved the problem.

Upgraded what to 3.2.0? This plugin does not have a 3.2.0 yet..?
