### ISSUE TITLE
the word is not recognized CrossFilePicker

### ISSUE THREAD

**Issue by jpolocosme** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#205]
I have this code that they show in their library

```
try
            {
                FileData fileData = await CrossFilePicker.Current.PickFile();

                if (fileData == null)
                    return; // user canceled file picking

                string fileName = fileData.FileName;

            }
            catch (Exception ex)
            {
                System.Console.WriteLine("Exception choosing file: " + ex.ToString());
            }
```

I install fine from the visual studio but CrossFilePicker 
It marks me in red and there is no solution to call some "using"
help me pls!

**Comment by vividos** [comment]
Did you install the NuGet package? It should then be available. You can see which `using` is necessary in the sample project in this GitHub repository.

**Comment by jpolocosme** [comment]
yes, install the nugget, but CrossFilePicker not recognized by the nugget

**Comment by jpolocosme** [comment]
just need to install the nugget?
should I import the github repository into my project?

**Comment by vividos** [comment]
Yes, installing the NuGet package is enough.
