### ISSUE TITLE
 Is there way to save the chosen file to a device path

### ISSUE THREAD

**Issue by jpolocosme** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#206]
Thanks for creating this nugget,
is there way to save the chosen file to a device path

**Comment by jpolocosme** [comment]
what happens is that, I need to choose a .p12 file and save it in some path, so it is not only to see its content and copy it to another file to replace this, but to choose it and save that same one.

**Comment by jpolocosme** [comment]
after many attempts this served me:

string objrute = Path.Combine(rute.path_cert, fileData.FileName);
File.WriteAllBytes(objruta, fileData.DataArray);

**Comment by vividos** [comment]
That's the way. You can also use result.GetStream() and use Stream.CopyTo(), if you want to go async.

**Comment by jpolocosme** [comment]
Gracias, saludos.

**Comment by vividos** [comment]
You're welcome. By the way, it's actually Stream.CopyToAsync(), and there you can also specify a CancellationToken, e.g. for a progress dialog where the user can cancel the copying.
