### ISSUE TITLE
Android version 9 and above not supported images upload

### ISSUE THREAD

**Issue by ghotekarduryo** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#208]
FileData file = await CrossFilePicker.Current.PickFile();
                We Are Used Filepicker on Image Upload  file selection and upload successfully on android version 6,7,8 
but not working on version on 9 and above

Thanks  in advance

**Comment by jfversluis** [comment]
Closing this since this project will retire, please check out [Xamarin.Essentials](https://github.com/xamarin/Essentials/tree/main/Xamarin.Essentials/FilePicker) which now has a FilePicker based on this one.
