### ISSUE TITLE
iOS vs Modal view not working

### ISSUE THREAD

**Issue by xacte-richard** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#21]
Icloud picker is opened but not visible.

So change like these is needed

this 
UIApplication.SharedApplication.KeyWindow.RootViewController.PresentViewController (documentPicker, true, null);

to
UIWindow window = UIApplication.SharedApplication.KeyWindow;
UIViewController viewController = window.RootViewController;

while (viewController.PresentedViewController != null)
           viewController = viewController.PresentedViewController;

viewController.PresentViewController(documentPicker, true, null);

//

and this
UIApplication.SharedApplication.KeyWindow.RootViewController.PresentViewController (importMenu, true, null);

to
UIWindow window = UIApplication.SharedApplication.KeyWindow;
UIViewController viewController = window.RootViewController;

while (viewController.PresentedViewController != null)
           viewController = viewController.PresentedViewController;

viewController.PresentViewController(importMenu, true, null);

**Comment by jfversluis** [comment]
Does it then still work correctly for non-modal screens?

**Comment by manonaga2188** [comment]
@xacte-richard  Thanks. Im also faced this issue. Not it has fixed.

**Comment by vividos** [comment]
This is fixed in the latest NuGet package 2.0.106-beta. Please try it out. Thanks!
