### ISSUE TITLE
Picking files that are not images throws: Java.Lang.NullPointerException: uri  

### ISSUE THREAD

**Issue by podger** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#210]
Hello!
I'm having issues with picking files on Android, image seems to work fine and get picked without problems but with the rest of types throws exception (I tried with PDF and .ico file).
- I installed the plugin in all the projects.
- I enabled READ_EXTERANL_STORANGE & WRITE_EXTERNAL_STORAGE permissions. 

The code is pretty much the one I copied in the README.
```
        async Task ImportFile(object id)
        {
            if (IsBusy)
                return;

            IsBusy = true;


            try
            {
                FileData fileData = await CrossFilePicker.Current.PickFile();
                if (fileData == null)
                    return; // user canceled file picking

                string fileName = fileData.FileName;


                await PersonalDocumentsSvc.ImportFile(fileName, fileData.DataArray);


            }
            catch (Exception ex)
            {
                Crashes.TrackError(ex);
            }
            finally
            {
                IsBusy = false;
            }
        }
```

When I file that is not an image the method **PickFile()** it throws an exception: **Java.Lang.NullPointerException: uri**
Full Stack:
![image](https://user-images.githubusercontent.com/7222863/96251383-aad9e700-0fb0-11eb-8b05-0ae69eba5aff.png)

## Specifications
I tried different combination of Nuget Package (2.134 and the latest) with Xamarin.Forms, but all combinations produce the same result.
  - NuGet package version: 2.1.34+
  - Platform(s):  Xamarin Forms: 4.8.0.x / Android 10 / API 30
![image](https://user-images.githubusercontent.com/7222863/96250036-7bc27600-0fae-11eb-9b99-6619f7c0450f.png)

**Comment by jfversluis** [comment]
Hey @podger sorry about that! Unfortunately, this library is about to be retired. Xamarin.Essentials now has a FilePicker, based on a big part of our library, and that it where the future will be. I suggest trying that library and if you're seeing the same thing opening an issue there.

**Comment by podger** [comment]
Hi @jfversluis, thanks for the quick reply.
I was waiting for the Xamarin.Essentials 1.6 stable release first before upgrading.
Anyway I tried the 1.6.0-pre-2 and seems to work solving this issue. I guess I will follow this way.

Thanks.

**Comment by jfversluis** [comment]
Closing this since this project will retire, please check out [Xamarin.Essentials](https://github.com/xamarin/Essentials/tree/main/Xamarin.Essentials/FilePicker) which now has a FilePicker based on this one.
