### ISSUE TITLE
 Multiple Selection 

### ISSUE THREAD

**Issue by Denaindra** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#25]
Is there any possibility select multiple file ...

**Comment by jfversluis** [comment]
Not right now

**Comment by abdullam09** [comment]
Hi,
Is this feature gonna be available soon?

**Comment by jfversluis** [comment]
Wouldn’t count on it. Done when it’s done!

**Comment by vividos** [comment]
@abdullam09 It's an open source project, so you can jump in and develop the feature yourself. I think the Issues marked as "enhancement" are more seen as wishes. The advantage of this project is that your PR is actually considered and integrated some time soon :-)

**Comment by aismaniotto** [comment]
+1

**Comment by FreakyAli** [comment]
+1

**Comment by FetFrumos** [comment]
+1

**Comment by vividos** [comment]
Notice that this feature request is up for grabs. I don't need multi selection in pay project, so I will not develop this feature in the foreseeable future, and I think jfversluis is also occupied. Nevertheless, pull requests are welcome!

**Comment by amirvenus** [comment]
I have implemented this featuer myself in UWP as one of my clients needed it. 

It was super easy in UWP but I don't know how easy it is in iOS, Android, WPF and macOS.

I will file a PR when I have added all platforms.

**Comment by vividos** [comment]
You can already make a PR now and push changes as you go. This way we can discuss the API and the implementation right now

**Comment by amirvenus** [comment]
Hi ok I will do that today when I get home. 

UWP part is done and is fully working!

I am a bit struggling with Android part so hopefully you can help me with that part. 

Thanks!

**Comment by vividos** [comment]
I just implemented multiple selection for the file picker proposal in Xamarin Essentials, you might borrow the implementation from there: https://github.com/xamarin/Essentials/pull/1147

**Comment by jfversluis** [comment]
Closing this since this project will retire, please check out [Xamarin.Essentials](https://github.com/xamarin/Essentials/tree/main/Xamarin.Essentials/FilePicker) which now has a FilePicker based on this one.
