### ISSUE TITLE
Error when referencing package from macOS project

### ISSUE THREAD

**Issue by aloisdeniel** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#27]
I have a .NET Standard library that references the NuGet package `Xamarin.Plugin.FilePicker - v2.0.8-beta` and a macOS project that references this library (*and the same NuGet package, since transitive dependencies aren't supported on VS4Mac yet*).

The portable mocked implementations are used instead of the macOS ones and an exception is thrown.

I'm pretty sure it is because the macOS dll is named `Plugin.FilePicker.Mac.dll` instead of overriding the mocked `Plugin.FilePicker.dll`.

![image](https://user-images.githubusercontent.com/7687231/36164268-28008c00-10ec-11e8-8424-f82e7e4fd522.png)

**Comment by jfversluis** [comment]
Hm, that shouldn't happen. Let me see if I can fix that, thanks!

**Comment by jfversluis** [comment]
I tried to fix it, could you try this one from the development feed: https://ci.appveyor.com/api/buildjobs/e6vr1xis0og1apb6/artifacts/Xamarin.Plugin.FilePicker.2.0.16-beta.nupkg

**Comment by aloisdeniel** [comment]
It works now with this version! Thanks @jfversluis!

**Comment by jfversluis** [comment]
Glad to be of service! I will push this to NuGet.org as a new beta package so you're not stuck with this standalone one.
