### ISSUE TITLE
Add more sample projects

### ISSUE THREAD

**Issue by jfversluis** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#3]
The library targets more platforms than the sample projects that are added right now.

It would be great to have Windows, UWP and Mac OS sample projects.

**Comment by jfversluis** [comment]
Added Mac OS sample

**Comment by vividos** [comment]
I've added an UWP sample project, but it's based on PR #91 where PackageReferences are used.

**Comment by vividos** [comment]
The UWP sample project was added. Now a WPF sample project would be good :-)

**Comment by vividos** [comment]
I added a WPF sample project and the WPF implementation from #64. I guess we can close this ticket?

**Comment by jfversluis** [comment]
Agreed!
