### ISSUE TITLE
File picker cancel causes error

### ISSUE THREAD

**Issue by IeuanWalker** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#31]
Xamarin.forms android
Plugin - v1.2.1

If the user cancels selecting a file it causes a null reference exception

Here is my code -

```
try
{
        UserDialogs.Instance.ShowLoading("Loading");
        selectedFile = await CrossFilePicker.Current.PickFile();
}
catch (Exception ex)
{
        System.Diagnostics.Debug.WriteLine(ex);
}
finally
{
        UserDialogs.Instance.HideLoading();
}

if (selectedFile != null)
{
        // do stuff with file
}
// End of method where error is triggered
```

Here is the crash report from AppCentre
![image](https://user-images.githubusercontent.com/6544051/36255555-67bd3b3e-1247-11e8-9b21-739da3615da7.png)

**Comment by jfversluis** [comment]
I see you're mentioning version 1.2.1.
There are newer versions available of my NuGet package. Could you please try the latest version of this one to verify if this is still current?

**Comment by IeuanWalker** [comment]
@jfversluis I've just tried v2.0.20-beta and get the same error.
It's a strange error to replicate it -

1. Open file picker (press the back button - without choosing a file) > Open file picker (select a file) > NullReferenceException

2. Open file picker (select a file) > Open file picker (press the back button - without choosing a file) > NullReferenceException

**Comment by vividos** [comment]
I can reproduce this bug, it's also happening with the sample project in this github repository. Here's the code that crashes:

            var pickedFile = await CrossFilePicker.Current.PickFile();

            FileNameLabel.Text = pickedFile.FileName;  // <-- crash here
            FilePathLabel.Text = pickedFile.FilePath;

The PickFile() call returns a null reference when the user didn't choose a file. So check before accessing returned data.
