### ISSUE TITLE
In UWP PickFile() , could call FutureAccessList.Add with metadata ?

### ISSUE THREAD

**Issue by ldw9981** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#34]
it possible to open stream by file path when open it with no dialog.
example, when app start it possible to open file  programmatically. 

like this.

       public async Task<FileData> PickFile()
FutureAccessList.Add(file,file.Path);

        public async Task<Stream> OpenStream(string filePath)
        {
            Windows.Storage.StorageFile sfile = null;
            foreach (var item in StorageApplicationPermissions.FutureAccessList.Entries)
            {
                if( item.Metadata == filePath )
                {
                    sfile = await StorageApplicationPermissions.FutureAccessList.GetFileAsync(item.Token);
                    break;
                }
            }
            if (sfile == null)
                return null;

           return await sfile.OpenStreamForReadAsync();
        }

**Comment by jfversluis** [comment]
I'm sorry, but I'm not sure on what you're trying to achieve here?

**Comment by ldw9981** [comment]
surely i can use open stream by FileData.GetStream() after call FilePicker().

i want to only get file path and then i  want app to open stream when it start. 

 is this not appropriate purpose on project?

**Comment by jfversluis** [comment]
This project is meant to provide you with a dialog to let the user pick a file. That it should be able to do. Picking a file without a dialog is just finding a file programmatically, right? You don't need any library to do that. 

Or maybe I still don't understand what you are trying to do.

**Comment by ldw9981** [comment]
As far as I know, By default UWP not allow app to access file created by other app. However, it allow to gain permission by use Windows.Storage.Pickers.FileOpenPicker and FutureAccessList.  So project use it. 

Unfortunately  after calling Plugin.FilPicker,  In My App side ,i cant use token of access list (return value of FutureAccessList.Add ) . because it not be distinguished. if you could call add with metadata(filepath) i expect finding token and using token.  token will be used when open file stream next.

if you have time could you read this page?
https://docs.microsoft.com/en-us/windows/uwp/files/quickstart-using-file-and-folder-pickers

thanks to read and reply

**Comment by vividos** [comment]
@ldw9981 If I understand you correctly, you'd like the plugin to call FutureAccessList.Add() when picking the fil? As far as I can see, this is already implemented, here:
https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/blob/develop/src/Plugin.FilePicker/Plugin.FilePicker.UWP/FilePickerImplementation.cs#L51
Is this what you had in mind for the plugin to do? Otherwise we would need a code example of what you want us to do. Thanks!

**Comment by jfversluis** [comment]
If this is not implemented as you expect or you would like to see something different, please open another issue. Thanks!
