### ISSUE TITLE
On iOS Nuget doesn't seem to bring in the FilePickerImplementation package

### ISSUE THREAD

**Issue by NoleHealth** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#36]
Using Nuget to add this package to my .NET Standard based Xamarin app, CrossFilePicker.Current does not return the iOS Implementation.

I just get the error:
`This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.`

If I try to add this line to my ApDelagate
`var p = new Plugin.FilePicker.FilePickerImplementation();`
FilePickerImplementation is not found.

I have tried removing and reading the Nugget packages but that did not help.
Thank you

**Comment by jfversluis** [comment]
Which version did you use? Did you check out the beta ones?

**Comment by NoleHealth** [comment]
No, I am just using the version v1.2.1. I see now you have 2.0.20 beta available.

**Comment by NoleHealth** [comment]
For now I am building the files from the master branch.  I reference the Abstractions dll in the .NET Standard project.  I reference the respective Implementation dlls in UPW/Android/iOS.  Then using NInject I inject the Implementation for IFilePicker for each platform.  Seems to be working except for OpenFile in Android.
([https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/issues/37](url))

**Comment by NoleHealth** [comment]
@jfversluis OpenFile (FileData fileToOpen) is calling itself recursively.  Also OpenFile (FileData fileToOpen) and OpenFile (string fileToOpen) are using ExternalStorageState rather than ExternalStorageDirectory.
Notice SaveFile is correctly using ExternalStorageDirectory.
With these changes OpenFile is now working for me on Android.
Thanks.
Fixes attached:
[FilePickerImplementation.cs.txt](https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/files/1757010/FilePickerImplementation.cs.txt)

**Comment by jfversluis** [comment]
Please see if it works with the latest beta packages, I think it should. If not, please submit a new issue.
