### ISSUE TITLE
On Android OpenFile seems to crash

### ISSUE THREAD

**Issue by NoleHealth** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#37]
Using v1.2.1 Compiling against Oreo
On Android OpenFile seems to crash. My app freezes. No exception is thrown.  I have tried opening jpg, pdf, txt files. I pass in a file name, a func to return the stream, and blank path.  From looking in the code passing a blank path should cause OpenFile to call SaveFile to save the file in the platform appropriate path.

I am guessing this has to do with trying to pass a file with Intent on SDK >= 24.

https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en
This link mentions the need to use FileProvider in SDK >= 24.

Using Xamarin's Device.OpenUri method I get the error "file:///storage/emulated/0/tmp6e4aa988.png exposed beyond app through Intent.getData()"

**Comment by jfversluis** [comment]
I know version 1.2.1 is bugged, I will take 2.0 out of beta soon.
1.2.1 is just the version taken from the original repo and has a lot of problems. Did you try if this is still current in the latest pre-release?

**Comment by NoleHealth** [comment]
@jfversluis 
OpenFile (FileData fileToOpen) is calling itself recursively.
OpenFile (FileData fileToOpen) and  OpenFile (string fileToOpen) are using Android.OS.Environment.ExternalStorageState to construct the path rather than ExternalStorageDirectory as the SaveFile method does.
Fix is below
Plugin.FilePicker.Android\FilePickerActivity.cs

`public void OpenFile (string fileToOpen)
        {
            var myFile = new File (Android.OS.Environment.ExternalStorageDirectory, fileToOpen);

            OpenFile (myFile);
        }

        public async void OpenFile (FileData fileToOpen)
        {
            var myFile = new File (Android.OS.Environment.ExternalStorageDirectory, fileToOpen.FileName);

            if (!myFile.Exists ())
                await SaveFile (fileToOpen);

            OpenFile (myFile);
        }`

**Comment by NoleHealth** [comment]
@jfversluis  I also have a fix for Android.OS.Build.VERSION.SdkInt >= Android.OS.BuildVersionCodes.N using FileProvider to create the uri to fix the  error:
> exposed beyond app through Intent.getData()

I will submit a pull request after more testing.
Thanks

**Comment by jfversluis** [comment]
I will gladly look at a PR that you have in the workings
