### ISSUE TITLE
.Net Standard compatability

### ISSUE THREAD

**Issue by learn9969** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#4]
Hi
Wondering if there is any plan to make it .net standard compatible.
Thanks

**Comment by jfversluis** [comment]
There are now! We definitely should!

I'll try to look into it, if you have any contributions I'll be happy to accept them

**Comment by andymac4182** [comment]
I have given this an initial go in #5

**Comment by vividos** [comment]
Hi, I converted @ArtjomP 's FilePicker version to use .NET Standard in this pull request: https://github.com/ArtjomP/FilePicker-Plugin-for-Xamarin-and-Windows/pull/4 I'll have a try at porting over the changes to this repository, as it seems it is a bit more active.

**Comment by vividos** [comment]
See pull request #20 on this project :-)

**Comment by jfversluis** [comment]
@andymac4182 @learn9969 support for .NET Standard should be added now with thanks to @vividos. Please try the package which is now in [2.0.2-beta](https://www.nuget.org/packages/Xamarin.Plugin.FilePicker/2.0.2-beta)

I will close this issue, if anything comes up, please open a new one.
