### ISSUE TITLE
No file returned in iOS

### ISSUE THREAD

**Issue by FocusTechnologyGroup** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#40]
I'm using v 1.2.1 in a Xamarin Forms app. Works perfectly in the android branch but in iOS nothing gets returned from the PickFile await. Here is the code from my event handler on a button:
FileData filedata = await CrossFilePicker.Current.PickFile();
                if (filedata != null)
                {
                   //do file stuff.
                }
iCloud opens and I can select a file but the filedata value is always null.

**Comment by jfversluis** [comment]
Please try the latest beta package and see if it is fixed

**Comment by FocusTechnologyGroup** [comment]
Works as expected with the latest beta. thanks. 👍

**Comment by jfversluis** [comment]
Glad to hear that!
