### ISSUE TITLE
CrossFilePicker returns null

### ISSUE THREAD

**Issue by bmcn99** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#41]
Here is how I use the plugin

using Plugin.FilePicker.Abstractions;
using Plugin.FilePicker;
[....]
FileData fileData = new FileData();
fileData = await CrossFilePicker.Current.PickFile();
[..work with fileData..]

It brings up the file picker, I choose a local, small file but when it returns fileData is null.

I copied the code from elsewhere in the project, on a different page and it does properly work there, but the same things that he did I am doing.

Does anyone know what would cause this or how to fix it?

**Comment by jfversluis** [comment]
Which version of the packages are you using?
Where is the file located that you are trying to pick?

**Comment by jfversluis** [comment]
@bmcn99 could you check if this is fixed with the latest beta package? If not, please open a new issue.
