### ISSUE TITLE
Problem getting the DataArray

### ISSUE THREAD

**Issue by CiaranC1** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#42]
I am trying to get DataArray from a pdf file on Android using this code -

```
FileData file = await CrossFilePicker.Current.PickFile();

if (file != null)
{
    string fileData = Convert.ToBase64String(file.DataArray);
}

```
It is producing an error "System.IO.DirectoryNotFoundException"

I am using the most recent beta after the latest stable version was giving me a blank DataArray.

I am using Xamarin PCL Project, and the pdf is from a Google Drive. It works fine with Images, the problem seems to be with PDF and Doc files.

The problem seems to be with the file path, it says that it is "/document/acc=3;doc=2"

How do I fix this problem?

**EDIT:**
The problem seems to be with Google Drive, does this support the use of Google Drive?

**Comment by jfversluis** [comment]
Should be fixed in the latest beta packages. Please check if that is the case. If not, please open another issue, thanks!

**Comment by CiaranC1** [comment]
It isn't OneDrive, it is Google Drive on Android, I haven't tried with OneDrive

**Comment by jfversluis** [comment]
According to @vividos the fixes should work for both Google Drive as well as OneDrive. Could you give it a go with this package: https://www.nuget.org/packages/Xamarin.Plugin.FilePicker/2.0.58-beta and let me know how it goes?

**Comment by CiaranC1** [comment]
Sorry, I had to Clean and rebuild but yes it is working now, Thank you

**Comment by jfversluis** [comment]
No worries, good to hear you've got it working, thanks for letting us know!
