### ISSUE TITLE
Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Application initializing document picker is missing the iCloud entitlement.

### ISSUE THREAD

**Issue by mayakhambhayata** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#43]
I have setup my iOS xamarin project and sets all the data in my application mentioned in below link:
https://docs.microsoft.com/en-in/xamarin/ios/data-cloud/intro-to-cloudkit

But now I am getting below error:

Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Application initializing document picker is missing the iCloud entitlement. Is com.apple.developer.icloud-container-identifiers set?
Native stack trace:
	0   CoreFoundation                      0x0000000185ace37c <redacted> + 148
	1   libobjc.A.dylib                     0x0000000184d14528 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000185ace238 <redacted> + 0
	3   Foundation                          0x00000001864697f4 <redacted> + 112
	4   UIKit                               0x000000018f77ff0c <redacted> + 300
	5   UIKit                               0x000000018f77f788 <redacted> + 228
	6   XamarinFilePickerTest.iOS           0x0000000102e038e8 XamarinFilePickerTest.iOS + 38582504
	7   XamarinFilePickerTest.iOS           0x0000000102245904 XamarinFilePickerTest.iOS + 26269956
	8   XamarinFilePickerTest.iOS           0x000000010321dfd0 XamarinFilePickerTest.iOS + 42885072
	9   XamarinFilePickerTest.iOS           0x000000010321f4e4 XamarinFilePickerTest.iOS + 42890468
	10  XamarinFilePickerTest.iOS           0x000000010322f334 XamarinFilePickerTest.iOS + 42955572
	11  XamarinFilePickerTest.iOS           0x000000010321d7d4 XamarinFilePickerTest.iOS + 42883028
	12  XamarinFilePickerTest.iOS           0x00000001009d0838 XamarinFilePickerTest.iOS + 624696
	13  XamarinFilePickerTest.iOS           0x0000000100ce697c XamarinFilePickerTest.iOS + 3860860
	14  XamarinFilePickerTest.iOS           0x00000001009cf8dc XamarinFilePickerTest.iOS + 620764
	15  XamarinFilePickerTest.iOS           0x0000000101dbbf94 XamarinFilePickerTest.iOS + 21512084
	16  XamarinFilePickerTest.iOS           0x000000010207e5b4 XamarinFilePickerTest.iOS + 24405428
	17  XamarinFilePickerTest.iOS           0x0000000102670b50 XamarinFilePickerTest.iOS + 30640976
	18  XamarinFilePickerTest.iOS           0x0000000100f0ebd4 XamarinFilePickerTest.iOS + 6122452
	19  XamarinFilePickerTest.iOS           0x0000000103273a7c mono_pmip + 22124
	20  XamarinFilePickerTest.iOS           0x00000001032e012c mono_pmip + 466204
	21  XamarinFilePickerTest.iOS           0x00000001032e008c mono_pmip + 466044
	22  XamarinFilePickerTest.iOS           0x000000010093d964 XamarinFilePickerTest.iOS + 22884
	23  XamarinFilePickerTest.iOS           0x0000000100942464 XamarinFilePickerTest.iOS + 42084
	24  UIKit                               0x000000018f0b96b4 <redacted> + 96
	25  UIKit                               0x000000018f0b9634 <redacted> + 80
	26  UIKit                               0x000000018f0a41dc <redacted> + 440
	27  UIKit                               0x000000018f0b8f28 <redacted> + 576
	28  UIKit                               0x000000018f714610 <redacted> + 4280
	29  UIKit                               0x000000018f70fbc0 <redacted> + 1224
	30  CoreFoundation                      0x0000000185a75edc <redacted> + 32
	31  CoreFoundation                      0x0000000185a73894 <redacted> + 412
	32  CoreFoundation                      0x0000000185a73e50 <redacted> + 1292
	33  CoreFoundation                      0x0000000185993e58 CFRunLoopRunSpecific + 436
	34  GraphicsServices                    0x0000000187840f84 GSEventRunModal + 100
	35  UIKit                               0x000000018f0e867c UIApplicationMain + 236
	36  XamarinFilePickerTest.iOS           0x0000000102dd9860 XamarinFilePickerTest.iOS + 38410336
	37  XamarinFilePickerTest.iOS           0x000000010263c0ac XamarinFilePickerTest.iOS + 30425260
	38  XamarinFilePickerTest.iOS           0x000000010263bf6c XamarinFilePickerTest.iOS + 30424940
	39  XamarinFilePickerTest.iOS           0x00000001009d0e40 XamarinFilePickerTest.iOS + 626240
	40  XamarinFilePickerTest.iOS           0x0000000100f0ebd4 XamarinFilePickerTest.iOS + 6122452
	41  XamarinFilePickerTest.iOS           0x0000000103273a7c mono_pmip + 22124
	42  XamarinFilePickerTest.iOS           0x00000001032e012c mono_pmip + 466204
	43  XamarinFilePickerTest.iOS           0x00000001032e2e0c mono_pmip + 477692
	44  XamarinFilePickerTest.iOS           0x000000010325c334 XamarinFilePickerTest.iOS + 43139892
	45  XamarinFilePickerTest.iOS           0x00000001033a0288 xamarin_localized_string_format_9 + 22244
	46  XamarinFilePickerTest.iOS           0x00000001009cef98 XamarinFilePickerTest.iOS + 618392
	47  libdyld.dylib                       0x00000001854b056c <redacted> + 4

  at ObjCRuntime.Runtime.ThrowNSException (System.IntPtr ns_exception) [0x00000] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/src/ObjCRuntime/Runtime.cs:362 
  at ObjCRuntime.Runtime.throw_ns_exception (System.IntPtr exc) [0x00000] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/runtime/Delegates.generated.cs:130 
  at (wrapper native-to-managed) ObjCRuntime.Runtime:throw_ns_exception (intptr)
--- End of stack trace from previous location where exception was thrown ---
  at (wrapper managed-to-native) ObjCRuntime.Messaging:IntPtr_objc_msgSend_IntPtr_UInt64 (intptr,intptr,intptr,ulong)
  at UIKit.UIDocumentMenuViewController..ctor (System.String[] allowedUTIs, UIKit.UIDocumentPickerMode mode) [0x0003e] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/src/build/ios/native/UIKit/UIDocumentMenuViewController.g.cs:97 
  at Plugin.FilePicker.FilePickerImplementation.TakeMediaAsync () [0x000d0] in <799da471af454715a51db03b24fc1ccb>:0 
  at Plugin.FilePicker.FilePickerImplementation+<PickFile>d__11.MoveNext () [0x00011] in <799da471af454715a51db03b24fc1ccb>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <bdb3aaa208384edf9f1266721cf8f9c1>:0 
  at XamarinFilePickerTest.Page1+<btn_Clicked>d__1.MoveNext () [0x00049] in H:\Gorden\xamarin sample\test1\XamarinFilePickerTest\XamarinFilePickerTest\XamarinFilePickerTest\Page1.xaml.cs:28 	0   CoreFoundation                      0x0000000185ace37c <redacted> + 148
	1   libobjc.A.dylib                     0x0000000184d14528 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000185ace238 <redacted> + 0
	3   Foundation                          0x00000001864697f4 <redacted> + 112
	4   UIKit                               0x000000018f77ff0c <redacted> + 300
	5   UIKit                               0x000000018f77f788 <redacted> + 228
	6   XamarinFilePickerTest.iOS           0x0000000102e038e8 XamarinFilePickerTest.iOS + 38582504
	7   XamarinFilePickerTest.iOS           0x0000000102245904 XamarinFilePickerTest.iOS + 26269956
	8   XamarinFilePickerTest.iOS           0x000000010321dfd0 XamarinFilePickerTest.iOS + 42885072
	9   XamarinFilePickerTest.iOS           0x000000010321f4e4 XamarinFilePickerTest.iOS + 42890468
	10  XamarinFilePickerTest.iOS           0x000000010322f334 XamarinFilePickerTest.iOS + 42955572
	11  XamarinFilePickerTest.iOS           0x000000010321d7d4 XamarinFilePickerTest.iOS + 42883028
	12  XamarinFilePickerTest.iOS           0x00000001009d0838 XamarinFilePickerTest.iOS + 624696
	13  XamarinFilePickerTest.iOS           0x0000000100ce697c XamarinFilePickerTest.iOS + 3860860
	14  XamarinFilePickerTest.iOS           0x00000001009cf8dc XamarinFilePickerTest.iOS + 620764
	15  XamarinFilePickerTest.iOS           0x0000000101dbbf94 XamarinFilePickerTest.iOS + 21512084
	16  XamarinFilePickerTest.iOS           0x000000010207e5b4 XamarinFilePickerTest.iOS + 24405428
	17  XamarinFilePickerTest.iOS           0x0000000102670b50 XamarinFilePickerTest.iOS + 30640976
	18  XamarinFilePickerTest.iOS           0x0000000100f0ebd4 XamarinFilePickerTest.iOS + 6122452
	19  XamarinFilePickerTest.iOS           0x0000000103273a7c mono_pmip + 22124
	20  XamarinFilePickerTest.iOS           0x00000001032e012c mono_pmip + 466204
	21  XamarinFilePickerTest.iOS           0x00000001032e008c mono_pmip + 466044
	22  XamarinFilePickerTest.iOS           0x000000010093d964 XamarinFilePickerTest.iOS + 22884
	23  XamarinFilePickerTest.iOS           0x0000000100942464 XamarinFilePickerTest.iOS + 42084
	24  UIKit                               0x000000018f0b96b4 <redacted> + 96
	25  UIKit                               0x000000018f0b9634 <redacted> + 80
	26  UIKit                               0x000000018f0a41dc <redacted> + 440
	27  UIKit                               0x000000018f0b8f28 <redacted> + 576
	28  UIKit                               0x000000018f714610 <redacted> + 4280
	29  UIKit                               0x000000018f70fbc0 <redacted> + 1224
	30  CoreFoundation                      0x0000000185a75edc <redacted> + 32
	31  CoreFoundation                      0x0000000185a73894 <redacted> + 412
	32  CoreFoundation                      0x0000000185a73e50 <redacted> + 1292
	33  CoreFoundation                      0x0000000185993e58 CFRunLoopRunSpecific + 436
	34  GraphicsServices                    0x0000000187840f84 GSEventRunModal + 100
	35  UIKit                               0x000000018f0e867c UIApplicationMain + 236
	36  XamarinFilePickerTest.iOS           0x0000000102dd9860 XamarinFilePickerTest.iOS + 38410336
	37  XamarinFilePickerTest.iOS           0x000000010263c0ac XamarinFilePickerTest.iOS + 30425260
	38  XamarinFilePickerTest.iOS           0x000000010263bf6c XamarinFilePickerTest.iOS + 30424940
	39  XamarinFilePickerTest.iOS           0x00000001009d0e40 XamarinFilePickerTest.iOS + 626240
	40  XamarinFilePickerTest.iOS           0x0000000100f0ebd4 XamarinFilePickerTest.iOS + 6122452
	41  XamarinFilePickerTest.iOS           0x0000000103273a7c mono_pmip + 22124
	42  XamarinFilePickerTest.iOS           0x00000001032e012c mono_pmip + 466204
	43  XamarinFilePickerTest.iOS           0x00000001032e2e0c mono_pmip + 477692
	44  XamarinFilePickerTest.iOS           0x000000010325c334 XamarinFilePickerTest.iOS + 43139892
	45  XamarinFilePickerTest.iOS           0x00000001033a0288 xamarin_localized_string_format_9 + 22244
	46  XamarinFilePickerTest.iOS           0x00000001009cef98 XamarinFilePickerTest.iOS + 618392
	47  libdyld.dylib                       0x00000001854b056c <redacted> + 4
}

**Comment by jfversluis** [comment]
What version of the package are you using? Did you notice the beta packages?

**Comment by mayakhambhayata** [comment]
I am using 2.0.8-beta only.

**Comment by mayakhambhayata** [comment]
Thanks done. Actually we need to enabled icloud from apple site too.
