### ISSUE TITLE
File Picker Save As

### ISSUE THREAD

**Issue by ldrapal** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#53]
## Expected Behavior
I would like to save a file, on android, by using a dialog picker to chose the folder location.  In UWP, it's very simple.. var savePicker = new Windows.Storage.Pickers.FileSavePicker();
I can't seem to find any code to do this in android.  This plug-in is the closest I have seen.

Is there a way to do this or does this plugin pick files only to open?

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - NuGet package version: 2.0.49-beta
  - Platform(s):

**Comment by vividos** [comment]
The FilePicker plugin is only designed to pick existing files. The different platforms have different ways to accomplish what you want to do, or don't have a way at all. On Android and iOS there's the "share" mechanism, on UWP and WPF you can access the file system directly. Nevertheless, if you come up with an implementation that's platform neutral, we would be happy to accept PR's to implement that. Thanks!
