### ISSUE TITLE
Empty data array on Min. Android API Level 23

### ISSUE THREAD

**Issue by RalphHerold** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#55]
## Expected Behavior

PCL project, Android smartphone running Android 7.0:

While the Minimum Android version in projects Manifest settings is set to Android 5.1 (API 22), the PickFile Method delivers a correctly filled data array. When i switch over to minimum Android version 6.0 (API 23), the filename is still returned correctly but the data array is empty.

- This happens with the last stable version 1.2.1 as well as with the prerelease v2.0.58-beta.
- And no: READ/WRITE EXTERNAL STORAGE Attribute are actually set!

## Steps to Reproduce the Problem

  1. 
  1.
  1.

## Specifications

  - NuGet package version:
  - Platform(s):

**Comment by jfversluis** [comment]
Thanks for reporting! This seems weird, so just switching the minimum Android version breaks the data array?

**Comment by RalphHerold** [comment]
Hi Gerald,

yes, indeed: I can directly switch between the minimum version 5.1 and 6.0, with 5.1 setting, the method return the data array correctly,
switching forward to 6.0, the array is reproducible empty. Switching back, it inherits correct data again.

I tested this with several physical Android 6, 7 and 8 devices, f.e.:

- Samsung A5(2016) (Android 7.0)
- Huawei P10 Lite (Android 7.0)
- Samsung Galaxy 8 , (Android 8)
- Honor 6X LTE (Android 6.0)
- Lenovo Tab4 10plus (Android 7.1)

I wonder why i seems to be the only person which faces this fundamental problem (?) but I really don’t know what i could have made wrong…

Thanks in advance,
Ralph

**Comment by jfversluis** [comment]
Thanks for the extra info! I will try to look into this as soon as possible

**Comment by dgboss** [comment]
I can confirm that I am seeing this exact same issue in v1.2.1, I haven't tried the beta yet.

**Comment by jDuarte94** [comment]
Hi, 
Having the same problem here.
The array is empty, Length is 0 and Rank is 1 and the DataArray return me a empty array. 
Thanks in advance,

**Comment by YGuerin** [comment]
I have the same problem with a Xamarin.Android + Shared (not PCL) project.
I've tried with Minimum Version 21 (5.0), 22 (5.1) and 23 (6.0) => same result, some files have DataArray is set to byte[0]
The file didn't had spaces in its file name but I tried to rename it to "testfile.jpg" => the file seems to be corrupted since then (It was not the case before, I could see it in the native gallery). I can still see the preview on the file picker but every time I choose it, the DataArray is empty
I tried with a fresh new picture taken from camera, with every android minimum version and even with a rename => works very well

I hope those informations will help

**Comment by vividos** [comment]
Yes, switching your target version to Android 6.0 (Marshmallow) triggers this. Android treats your app as playing by the rules of Android 6.0, so you just have to do that. Starting with Marshmallow you don't only have to have READ_EXTERNAL_STORAGE for accessing the picked files, you also have the user ask for permission at runtime. I added a note to the front README for this project and also added code to the sample project to show how to do it:
https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/blob/develop/samples/Plugin.FilePicker.Sample.Forms/Forms/MainPage.xaml.cs

**Comment by vividos** [comment]
Note that we just released a new NuGet package 2.0.106-beta which has some Android related bug fixes as well, so check out this version. Thanks!

**Comment by vividos** [comment]
This issue should be fixed with the latest NuGet package. If not, please reopen this issue or add a new one. Thanks!
