### ISSUE TITLE
Picking file in IOS

### ISSUE THREAD

**Issue by jcardona6113** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#56]
## Actual Behavior
EDIT:
Really the problem is when i try to laod a file in a iphone using the icloud, the method, returns empty  array of bytes.

## Steps to Reproduce the Problem:

To select the file on the two platforms (Android and IOS) I am using the following syntax:

var filedata = await CrossFilePicker.Current.PickFile();
                NombreArchivo1 = filedata.FileName;

                if (!String.IsNullOrEmpty(NombreArchivo1))
                {
                    string ext = Path.GetExtension(NombreArchivo1).ToLower();

                        if (ext != ".jpg" &&
                            ext != ".png" &&
                            ext != ".pdf" &&
                            ext != ".xls" &&
                            ext != ".xlsx"&&
                            ext != ".doc" && 
                            ext != ".docx")
                        {

                        await dialogService.ShowMessage("Cuidado Al Cliente", "El tipo de archivo seleccionado, es invalido.");
                        NombreArchivo1 = string.Empty;
                        ContenidoArchivo1 = string.Empty;
                        return;
                    }
                }

                ContenidoArchivo1 = Convert.ToBase64String(filedata.DataArray);
                if (ContenidoArchivo1.Length > 15000000)
                {
                    await dialogService.ShowMessage("Error", "El tamaño del archivo a adjuntar, debe ser inferior a 15 MB.");
                    ContenidoArchivo1 = string.Empty;
                    NombreArchivo1 = string.Empty;
                    return;

The question is, is it necessary to select the files in a different way than the one I am using for Android?.

## Specifications
  - NuGet package version:
  - Platform(s): Im Using the nuget 2.0.58.0 Versión.

thanks for your help.

**Comment by jfversluis** [comment]
I'm not sure if this has anything to do with the library. The file is opened the right way and converting to Base64 isn't something that we provide.

In an attempt so still help you: doesn't it work with all images you select through the file picker? If you use this same image that is not working through a sample C# application that converts it to base64 for you doesn't it work then as well?

Just trying to eliminate some possibilities and see if it has to do with the file picker or the image or something else altogether.

**Comment by jcardona6113** [comment]
Thanks for your answer, the conversion to base 64 is for a specific requirement,
and it does not matter, but I discovered that when loading a file in IOS,
using ICloud I can only get the name of the file,
since when trying to get the bytes of the loaded file,
they do not correspond to the bytes of the file, they are incorrect, I have updated to the latest version in beta 2.0.64.0
and I have the same problem.

>> I tried to load with the same image in android and it works correctly.

**Comment by jcardona6113** [comment]
Please help

**Comment by requenaxii** [comment]
same problem here. @jcardona6113 did you get with any solution? Will be appreciate a workaround.

**Comment by vividos** [comment]
Can you try with the latest NuGet package 2.0.106-beta? I got some iOS fixes in that should fix the issue. The FilePath property should be set correctly. Even better, use the fileData.GetStream() method.

Also note that if you only want to let the user select images, you can now specify MIME types on Android and UTType values on iOS to disable selecting files that are not interesting to you. See sample code here:
https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/blob/develop/samples/Plugin.FilePicker.Sample.Forms/Forms/MainPage.xaml.cs

**Comment by vividos** [comment]
This issue should be fixed with the latest NuGet package. If not, please reopen this issue and comment or add a new issue. Thanks!
