### ISSUE TITLE
some file disabled

### ISSUE THREAD

**Issue by Nikdm46** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#59]
When browsing for doc from iCloud Drive in iPhone some document are disabled(xls,doc)

  - 2.0.64:
  - ios 10+:

**Comment by vividos** [comment]
FilePicker has a mechanism to filter for files to be selected, e.g. on iOS based on UTType-values. The default values in the iOS implementation should select all files, but it may be that some files were excluded. The filtering was extended in the later releases 2.0.81 and 2.0.106. Could you try again with the latest beta package? All files should be shown as enabled unless you specify some UTType values. See the sample code for an example:
https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/blob/develop/samples/Plugin.FilePicker.Sample.Forms/Forms/MainPage.xaml.cs

**Comment by vividos** [comment]
The PickFile() parameters to specify file types for picking is now documented in the README of this repository.
