### ISSUE TITLE
Is support for Windows Phone needed?

### ISSUE THREAD

**Issue by andymac4182** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#6]
Not sure if this is required since Microsoft is starting to push hard on other platforms now and really depreciated Windows Phone. https://www.engadget.com/2017/07/11/windows-phone-support-ends/

**Comment by jfversluis** [comment]
As far as I am concerned we can drop it.

I just took the snapshot from the original repo. But I agree it can be dropped.

**Comment by jfversluis** [comment]
In 2.0.2-beta support for this was dropped
