### ISSUE TITLE
File picker displays virtual files and freezes when choosing one.

### ISSUE THREAD

**Issue by LukasBerulis** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#60]
## Expected Behavior
Not show or get the virtual file.
## Actual Behavior
In Android, the file picker lists virtual files from google drive which aren't actually on the device together with all the files. After selecting the google drive file the picker freezes for a couple of seconds and returns null.

## Steps to Reproduce the Problem

  1. PickFile()
  2. Select virtual file

## Specifications

  - NuGet package version: 2.0.64-beta
  - Platform(s): Android

**Comment by jfversluis** [comment]
You mean files stored on Google Drive or similar that first need to be downloaded?

**Comment by LukasBerulis** [comment]
Yes. I have solved the problem by adding an extra boolean to the file picker intent to only display files on the device.

**Comment by jfversluis** [comment]
Glad to hear you've found a workaround, but it still would be nice if it worked

**Comment by vividos** [comment]
This issue should be fixed with the latest NuGet package. If not, please reopen this issue and comment or add a new issue. Thanks!
