### ISSUE TITLE
object not set to an instance of an object

### ISSUE THREAD

**Issue by abrantie1z** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#61]
## Expected Behavior
when pickFile() is called, it is supposed to show the file system where user either choses a file or not.

## Actual Behavior
when PickFile() is called and the user first select a file, and PickFile() is called again, but this time user doesnt select a file, a null reference exceptio is thrown.

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - NuGet package version:2.0.64-beta
  - Platform(s):Xamarin.Forms

**Comment by jfversluis** [comment]
Does this happen on iOS and Android?

**Comment by abrantie1z** [comment]
On Android

**Comment by vividos** [comment]
Can you provide us with the complete call stack, e.g. what the debugger says when you watch ex.StackTrace, or even better ex.ToString().

We also just released a new NuGet package 2.0.106-beta. Can you still reproduce the crash with this version? Thanks!

**Comment by vividos** [comment]
I explained this issue in the README of this project. Basically it means that you should catch any exceptions that might come from PickFile(), DataArray or GetStream() and see in the exception object what's wrong. Most probably it is that you didn't request read permission from the user on Android. I also explained this on the README and also added some code to the sample project. Please check it out. If this doesn't fix your problem, either open another issue or reopen and comment on this one. Thanks!

**Comment by abrantie1z** [comment]
Ok sir. Been a long time so used another plugin. But will recheck and give you feedback to help better your plugin. thanks for the time.

**Comment by jfversluis** [comment]
Please do, that would be great, thank you.

Just out of curiosity, which other plugin are you using?
