### ISSUE TITLE
Implement WPF support

### ISSUE THREAD

**Issue by jfversluis** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#64]
Since Xamarin.Forms now supports WPF, it would be great to have support for that in this plugin.

**Comment by BerndtHamboeck** [comment]
using Plugin.FilePicker.Abstractions;
using System;
using System.Diagnostics;
using System.IO;
using System.Threading.Tasks;

namespace Plugin.FilePicker
{
    class FilePickerImplementation : IFilePicker
    {
        public void OpenFile(string fileToOpen)
        {
            try
            {
                if (File.Exists(fileToOpen))
                {
                    Process.Start(fileToOpen);
                }
            }
            catch (Exception ex)
            {
            }
        }

        public async void OpenFile(FileData fileToOpen)
        {
            try
            {

                if (!File.Exists(fileToOpen.FileName))
                    await SaveFile(fileToOpen);

                Process.Start(fileToOpen.FileName);

            }
            catch (Exception ex)
            {
            }
        }

        public Task<FileData> PickFile(string[] allowedTypes = null)
        {
            Microsoft.Win32.OpenFileDialog picker = new Microsoft.Win32.OpenFileDialog();
            picker.InitialDirectory = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);

            if (allowedTypes != null)
            {
                foreach (var type in allowedTypes)
                {
                    //TODO: filetypes
                }
            }
            var result = picker.ShowDialog();

            if (result == null || result == false)
                return null;

            var path = Path.GetDirectoryName(picker.FileName);
            var fileName = Path.GetFileName(picker.FileName);

            var data = new FileData(picker.FileName, fileName, () => File.OpenRead(picker.FileName), (x) => { });
            return Task.FromResult(data);

        }

        public async Task<bool> SaveFile(FileData fileToSave)
        {
            try
            {
                using (FileStream sourceStream = new FileStream(fileToSave.FilePath, FileMode.Create, FileAccess.Write, FileShare.None, bufferSize: 4096, useAsync: true))
                {
                    await sourceStream.WriteAsync(fileToSave.DataArray, 0, fileToSave.DataArray.Length);
                };
                return true;
            }
            catch (Exception ex)
            {
                return false;
            }
        }
    }
}

**Comment by jfversluis** [comment]
If you'd put it in a PR you will get the credits! :)

Thanks for your efforts either way

**Comment by vividos** [comment]
I implemented this in 2.0.116-beta, available from the AppVeyor build. @BerndtHamboeck  thanks for your code. If you'd like to get the credits in the NuGet package description, just tell us.
