### ISSUE TITLE
"Browse" dialog not apearing in Portrait but works in Landscape... or at all in older versions

### ISSUE THREAD

**Issue by StokedOnIt** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#66]
## Expected Behavior

"Browse" dialog appears in Portrait and Landscape mode on iOS

## Actual Behavior

"Browse" dialog only appears in Landscape mode but not portrait on iOS and is in the upper left corner

## Steps to Reproduce the Problem

I just used the sample code in my Xamarin forms app.

## Specifications

  - NuGet package version: Most tried up to 2.0.64 Beta, 1.2.1 the dialog does not appear at all.
  - Platform(s): iOS iPad

**Comment by Perkovsky** [comment]
I have analogical problem :(
How to fix this?

**Comment by vividos** [comment]
We just released NuGet package 2.0.106-beta. Can you reproduce this error with this latest package also?

**Comment by vividos** [comment]
In the newest NuGet package the plugin switched to using UIDocumentPickerViewController where there should be no more "browse" button step. The document picker is shown immediately. Please test with the newest NuGet package. Thanks!
