### ISSUE TITLE
How to create a dialog to create a file?

### ISSUE THREAD

**Issue by Happypig375** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#67]
## Expected Behavior
An alternative to a dialog to pick a file, aka a dialog to create a file, will also be present.

## Actual Behavior
Nothing can be used. Even trying to implement myself is really hard as I do not have devices on all the platforms.

## Steps to Reproduce the Problem

  1. Try to find an API to create a file
  2. Be disappointed

## Specifications

  - NuGet package version: 2.0.64-beta
  - Platform(s): All

**Comment by jfversluis** [comment]
I'm sorry but I don't quite understand what you are trying to achieve

**Comment by Happypig375** [comment]
Aka please provide an API for displaying a dialog asking the user to specify the path of the file to be created.

**Comment by jfversluis** [comment]
Not sure if this is even possible, but might be a nice feature.

**Comment by jfversluis** [comment]
I see this is the same as #72, closing this one in favor of that one for overview.
