### ISSUE TITLE
Readfully should close the stream

### ISSUE THREAD

**Issue by BerndtHamboeck** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#68]
Every time we access the DataArray the stream is opened. After reading from the specific implementation I believe the stream should be closed.

        public static byte[] ReadFully(Stream input)
        {
            using (var ms = new MemoryStream())
            {
                input.CopyTo(ms);
                input.Close(); //Close source file
                return ms.ToArray();
            }
        }

**Comment by jfversluis** [comment]
Good find! Did you actually run a memory profiler or such to verify this happening?

**Comment by BerndtHamboeck** [comment]
I use Xamarin Forms in WPF to build a new product for Android and iOS, because it’s quicker to test what I did and my file was locked.

So I tried the dispose, but this did not help me in any way as I do not have the stream in my hands. Then it was an easy find when I saw your code 😉

For the credits: No need to. The extension filter needs to be implemented anyway to be complete, I do not need it, that’s why it’s missing….

Thank you for your plugin! I *love* it on Android!!!

**Comment by vividos** [comment]
@BerndtHamboeck Thanks for the analysis! The stream passed to the ReadFully() method is not closed in the method itself, because you may reuse the stream in another place. The only one that calls the ReadFully() method is the DataArray property:

```
        public byte[] DataArray
        {
            get
            {
                using (var stream = GetStream())
                {
                    return ReadFully(stream);
                }
            }
        }
```

Do you also call ReadFully() from your code? Then maybe you should also use a using statement for this.

@jfversluis I would like to get rid of a public ReadFully() method and make it internal, as it's an implementation detail. What do you think?

**Comment by jfversluis** [comment]
Agreed, makes sense to not have this exposed in two different ways. It is a potential breaking change, so might be good to note that somewhere in the releases notes or similar.

**Comment by vividos** [comment]
I'll mark it obsolete and we can remove it in 2.1

**Comment by jfversluis** [comment]
Awesome! Are we ready to release this 2.0 as a non-beta?

**Comment by vividos** [comment]
I'd like to wait one more week if someone reports an issue, merge the WPF changes and release. Maybe merge the WPF changes now...

**Comment by jfversluis** [comment]
I guess this is done with all the new changes? If you disagree please reopen or open a new issue.

**Comment by vividos** [comment]
Yes it's done. I marked the method as obsolete and will set it to internal in 2.1
