### ISSUE TITLE
[Question] When support .net standard 2.0 official??

### ISSUE THREAD

**Issue by JaeWLee** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#69]
When this project support .net standard?? I love this repo
and
Do you have a plan that check file size

I appreciate what you have done.

**Comment by MookieFumi** [comment]
Yes, it's not fully compatible with .Net Standard v.2.0

![image](https://user-images.githubusercontent.com/4056557/43711137-14afab90-9972-11e8-94a6-6a0ac2d3dc7e.png)

**Comment by jfversluis** [comment]
Sorry for the late reply!

Thank you! I will look into the .NET Standard support. What do you mean about file size?

**Comment by DoumanAsh** [comment]
According to nuget it seems `2.0.0-beta` should support .NET Standard 2.0

**Comment by vividos** [comment]
All versions starting from 2.0.0 support .NET Standard. The NuGet packages are beta, so you have to check "Include prerelease" to see those packages.

**Comment by jfversluis** [comment]
So it is supported already, whenever we find this package is stable, we will take the beta tag off. Whenever that will be... /shrug 

In the meantime, you can use the beta packages and you will be notified automatically.
