### ISSUE TITLE
iOS Exception when filename contains space

### ISSUE THREAD

**Issue by raphaelsilvasage** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#70]
For iOS, when a file at iCloud has the filename containing space, it throws the exception:

"Could not initialize an instance of the type 'Foundation.NSUrl': the native 'initWithString:' method returned nil.\nIt is possible to ignore this condition by setting ObjCRuntime.Class.ThrowOnInitFailure to false."

**Comment by softsan** [comment]
same issue here, any suggestion to avoid the error? Thanks

**Comment by jfversluis** [comment]
Please provide some details on what version of the package you are using.

**Comment by softsan** [comment]
we are using v2.0.81-beta
Also getting following error on iOS (file.DataArray):
`System.IO.DirectoryNotFoundException: Could not find a part of the path "/private/var/containers/Bundle/Application/E6F13309-B18A-4905-96CB-55BFD8145F9F/myproject.app/file:/private/var/mobile/Containers/Data/Application/6EB34D7B-B279-4664-A758-FCC4478D095F/tmp/com.myproject-Inbox/sample.pdf".`

**Comment by vividos** [comment]
This is fixed in NuGet package 2.0.106-beta. Please try out this version. The FilePath property now returns a proper file system path.
