### ISSUE TITLE
Directory Browser to select a location for saving a file  

### ISSUE THREAD

**Issue by bharatdwarkani** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#72]
## Expected Behavior
It would be good if a feature is added to pick a directory location for saving a file. Similar to how a file is picked or if already possible then please provide suggestion on how to use it.

**Comment by craigchandler** [comment]
forking to add to uwp but ios and android maybe more work

**Comment by ghost** [comment]
directory location picker? if yours cannot do it - any suggestions? Need it For Xamarin.Forms Mac application.

**Comment by jfversluis** [comment]
This is not implemented (yet) and don’t know of any alternatives, sorry.

If you find anything we’ll be happy to hear it so we can get this started

**Comment by vividos** [comment]
A quick search found me this for Android:
https://stackoverflow.com/questions/27898676/simple-android-directory-picker-how#45366423
You can put it in a DependencyService class and call it from your Forms class. I don't know if there's a folder browsing metaphor - for picking files you can only access iCloud Drive files anyway.

**Comment by m33ts4k0z** [comment]
Cant you just add something like these:

```
            folderBrowser.ValidateNames = false;
            folderBrowser.CheckFileExists = false;
            folderBrowser.CheckPathExists = true;
```

So it will allow us to select a folder instead of a file? These are available on OpenFileDialog on C#.
A workaround that works fine on my desktop applications.

**Comment by broteam168** [comment]
You can use a library from my github:https://github.com/broteam168/Storage-Chooser-Xamarin.It is a library that binded from Java.And i think it's quite beautiful.Hope it helpful!

**Comment by jfversluis** [comment]
Closing this since this project will retire, please check out [Xamarin.Essentials](https://github.com/xamarin/Essentials/tree/main/Xamarin.Essentials/FilePicker) which now has a FilePicker based on this one.
