### ISSUE TITLE
Open a specified directory by default to pick files 

### ISSUE THREAD

**Issue by bharatdwarkani** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#73]
## Expected Behavior
Open a specified directory by default to pick files? Initial directory path can be passed as a parameter to a method.

**Comment by jfversluis** [comment]
Closing this since this project will retire, please check out [Xamarin.Essentials](https://github.com/xamarin/Essentials/tree/main/Xamarin.Essentials/FilePicker) which now has a FilePicker based on this one.
