### ISSUE TITLE
When I open for pick file and back without select file then again I want to choose file this show error

### ISSUE THREAD

**Issue by Rajanchauhan833** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#75]
## Expected Behavior
When FilePicker Open for Selecting File But I click on Back button without selecting any file. So After that Again I try to Pick file by Filepicker it does Open for Selecting File and I am able for Selecting File.

## Actual Behavior
When FilePicker Open for Selecting File But I click on Back button without selecting any file. So After that Again I try to Pick file by Filepicker it does not Open for Selecting File, it show process is in running.

## Steps to Reproduce the Problem

  1.After Back Button Press without Selecting File. FilePicker is not close the current running Process.
  2. Please Kill Process when back button Pressed. for I run again to choose file.  
  

## Specifications

  - NuGet package version:
  - Platform(s):

**Comment by Rajanchauhan833** [comment]
Please solve this issue

**Comment by jfversluis** [comment]
Please fill out the template for as much as possible.

**Comment by mkalletec** [comment]
Please solve this issue, we have tried everything.

**Comment by jfversluis** [comment]
If someone can give me a detailed report I would be happy to help. Can't do anything with this information I'm sorry.
