### ISSUE TITLE
[Improvement] When "could not initialize an instance of the type 'foundation.nsurl'" in iOS

### ISSUE THREAD

**Issue by JaeWangL** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#76]
If anyone have trouble with message "could not initialize an instance of the type 'foundation.nsurl'" in iOS,

You should change
**var url = new NSUrl(e.FilePath);**
to
**var url = new NSUrl(e.FilePath, false);**

in 

> Task<FileData> TakeMediaAsync(string[] allowedTypes)

I hope this helpful

**Comment by jfversluis** [comment]
Thanks! I think this can help solve a bug :)

**Comment by JaeWangL** [comment]
@jfversluis Thanks guys! I used this repo very well!! I love it

**Comment by vividos** [comment]
This bug is fixed in NuGet package 2.0.106-beta. Please try it out. FilePath now contains the full path, without file:// prefix.
