### ISSUE TITLE
System.NotImplementedException: This functionality is not implemented in the portable version of this assembly 

### ISSUE THREAD

**Issue by dush88c** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#78]
As I see this is an amazing plugin for Xamarin file picking in  Xamarin applications. Thanks for that.

I'm running Xamarin forms and installing NuGet package in PCL and in Droid project.
**CrossFilePicker.Current.PickFile()** giving the error.
When I used 2.0.8-beta, Application is crashed with an exception returning from this plugin.
Think this may happen because of Xamarine.forms version is not matching with plugin version.

How can I get resolved this?
Thanks

  - NuGet package version: 2.0.58
  - Platform(s): Xamarin.Form 2.4.0.280

**Comment by jfversluis** [comment]
This error happens when you execute the code form the shared code and not the project code. Make sure you have installed the plugin on both your shared, as well as the platform-specific project(s).

Also, thank you for your kind words and using the plugin!
