### ISSUE TITLE
Android FilePicker paths for OneDrive and Google Drive incomplete, iOS works

### ISSUE THREAD

**Issue by paulelong** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#79]
## Expected Behavior
The path returned from FilePicker should be something I can use to load the data in MediaPLayer or SimpleAudioPlayer, but for fiels on OneDrive this isn't the case.  The path returned by FilePicker for OneDrive works on iOS, but not on Android.  I suspect Google Drive has a similar issue, because the path is also short, but I haven't tested if it works on iOS.

## Actual Behavior
My goal is to save a path to a .wav file, so that it can be remembered and played.  This works as expected on iOS and OneDrive.  I can store the path, and use it directly with a Plugin.SimpleAudioPlayer media player.  But for Android and Google Drive, the path I receive looks incomplete, for instance /document/acc=2;doc=890.  And on OneDrive, the path looks like "/document/content://com.microsoft.skydrive.content.metadata/Drive/ID/1/Item/ID/11176/Property/?RefreshOption=AutoRefresh&RefreshTimeOut=15000".  When I use Android MediaPlayer.SetDataSourceAsync or Plugin.SimpleAudioPlayer to load the file, it fails with an exception.

## Steps to Reproduce the Problem

  1. Choose file from OneDrive with FilePIcker
  2. Use path to open file
  1. Works on iOS but not on Android

## Specifications

  - NuGet package version: v2.0.64-beta and 1.2.1
  - Platform(s): IOS, Android, UWP

**Comment by vividos** [comment]
I get that same problem on some corner case (I think it was OneDrive, too). We released NuGet package 2.0.106-beta, but I think this is not yet fixed. You can try out the latest package, though, if you like.

**Comment by vividos** [comment]
This issue should be fixed with the latest NuGet package. If not, please reopen this issue and comment or add a new issue. Thanks!
