### ISSUE TITLE
No browse button visible on a ipad

### ISSUE THREAD

**Issue by santoshg31** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#80]
## Expected Behavior
The browse button should come up on a ipad when I click on my  add file button.
Works fine on iphone.

## Actual Behavior
No browse button present on a ipad to select a file.However  I have noticed that the in landscape mode for ipad the browse button appears at top left corner.

## Specifications

  - NuGet package version: 2.0.64-Beta
  - Platform(s): ios

**Comment by sam9116** [comment]
I'm trying to work on a similar issue, but my goal is not to show the browse button at all and go directly to the file picker screen, or show multiple file provider options when hitting the browse button

**Comment by vividos** [comment]
I tested on an iPad with iOS 11 and didn't get this behavior. Could you test with the latest NuGet package 2.0.106-beta if it still happens? Which iOS version and device do you use? Thanks!

**Comment by sam9116** [comment]
I had the same problem on iOS 11.4 on an iPad 9.7 inch

**Comment by vividos** [comment]
@sam9116  did you test with the latest NuGet package?

**Comment by sam9116** [comment]
@vividos no it was just 2.0.64, I'll reintroduce the package into the solution tommrow and see what happens

**Comment by sam9116** [comment]
@vividos I no longer see a browse button, but got the iCloud file picker dialog directly, is that intended?
this also works regardless of screen orientation

**Comment by vividos** [comment]
A recent PR switched to UIDocumentPickerViewController, which directly shows the iCloud picker. Thanks for testing!
