### ISSUE TITLE
[Issue] FilePicker is not working in ModalPage (iOS only)

### ISSUE THREAD

**Issue by JaeWangL** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#82]
## Expected Behavior
working well in modalPage (iOS)

## Steps to Reproduce the Problem

  1. Navigate with **PushModalPage**
  2. Invoke 'await PickFile();'
  3. iCloud view is not appeared in iOS

## Specifications

  - NuGet package version: 2.0.64
  - Platform(s): iOS

**Comment by jfversluis** [comment]
Could you confirm this still happens in the latest package?

**Comment by JaeWangL** [comment]
@jfversluis Yes, I tested with 2.0.81. and had same issue

**Comment by mayurprasad** [comment]
Any update on this issue.? I am facing the same issue.

**Comment by vividos** [comment]
This is fixed in NuGet package 2.0.106-beta. Please try out.

**Comment by mayurprasad** [comment]
> 
> 
> This is fixed in NuGet package 2.0.106-beta. Please try out.

Thanks for the update. I have tested its working now.

**Comment by vividos** [comment]
Thanks for testing!
