### ISSUE TITLE
Android: Getting unauthorized exception

### ISSUE THREAD

**Issue by VansW** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#89]
## Expected Behavior
   FileData pickedFile = await CrossFilePicker.Current.PickFile();
      using (var memoryStream = new MemoryStream())
                        {
                            Attachment.GetStream().CopyTo(memoryStream);
                            Attachment.Dispose();
                            receiptFile.Stream =  memoryStream.ToArray();
                            receiptFile.FileSize = receiptFile.Stream.Length;
                        }

## Actual Behavior
Attachment.GetStream throws an error: UnauthorizedAccessException.  Access to the path "/storage/emulated/0/My Documents/ReportDoc.docx" is denied 

Please help what can be done here.

**Comment by vividos** [comment]
Do you add the READ_EXTERNAL_STORAGE permission to your project? Without it the Android implementation of the FilePicker plugin can't access the stored files.

**Comment by vividos** [comment]
Did you add the READ_EXTERNAL_STORAGE permission to your project? Without it the Android implementation of the FilePicker plugin can't access the stored files.

**Comment by VansW** [comment]
Yes, I added those permissions. I made it working by enabling the storage permissions on my phone.

**Comment by vividos** [comment]
Hmm maybe we should request permission inside the Android implementation. As far as I can see it doesn't need user input, only requesting the permission.

**Comment by VansW** [comment]
I'm not sure what is the difference but for Galaxy S7, we had to enable storage permissions for my app in the phone. But for some of the other android phones it worked without taking that action.

"We can request permission inside the Android Implementation. " What do you mean by that? 
Is it like using any permissions plugin, which takes user input?

**Comment by vividos** [comment]
Here's a StackOverflow question on the permission changes in Marshmallow (6.0):
https://stackoverflow.com/questions/33666071/android-marshmallow-request-permission

The Xamarin Permissions Plugin (https://github.com/jamesmontemagno/PermissionsPlugin) handles this nicely for us, but adding this would add a dependency from FilePicker to the permissions plugin.

**Comment by vividos** [comment]
I added a note to the README.md explaining that the permission must be requested by the user first. This should fix your problem.
