### ISSUE TITLE
Add tags for beta versions from NuGet

### ISSUE THREAD

**Issue by vividos** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#93]
I'm currently trying to troubleshoot the reported errors in the various tickets. It would be good if I could see which NuGet package versions map to which git repository commits. Could you maybe tag at least 2.0.64 and 2.0.81 in the repository? Thanks!

**Comment by jfversluis** [comment]
What do you want me to do?

**Comment by vividos** [comment]
I created a tag for the 2.0.106-beta NuGet package in the github repository. I hope this is in your interest.

I was having problems understanding which commit related to which beta version and wanted to check which changes were between 2.0.64 and 2.0.81, where the problems appeared. From reading the various issues I gained more understanding, so it's ok. If you like, you can tag previous buids, too, but I don't need the tags now.
